*Trabajo de Fin de Máster. Ingeniería del Software: Cloud, Datos y Gestión TI*

------

# Respuesta frente a la COVID-19: Un análisis de GitHub

##### *Jacinto José Ruiz Díaz*

## Capítulo 4.2. Búsqueda de repositorios

------

In [1]:
import requests
import json
import pandas as pd 
import time
from datetime import timedelta, datetime
import sys
pd.options.mode.chained_assignment = None
from pandasgui import show

### Creación de cabecera con token de identificación

In [2]:
token = "" # Rellenar con token generado en GitHub
header = {'Authorization': 'token %s' % token}

### Límites de consultas

In [4]:
limits = requests.get('https://api.github.com/rate_limit')
print(json.dumps(limits.json(), indent=4, sort_keys=True))

{
    "rate": {
        "limit": 60,
        "remaining": 60,
        "reset": 1630632389,
        "resource": "core",
        "used": 0
    },
    "resources": {
        "core": {
            "limit": 60,
            "remaining": 60,
            "reset": 1630632389,
            "resource": "core",
            "used": 0
        },
        "graphql": {
            "limit": 0,
            "remaining": 0,
            "reset": 1630632389,
            "resource": "graphql",
            "used": 0
        },
        "integration_manifest": {
            "limit": 5000,
            "remaining": 5000,
            "reset": 1630632389,
            "resource": "integration_manifest",
            "used": 0
        },
        "search": {
            "limit": 10,
            "remaining": 10,
            "reset": 1630628849,
            "resource": "search",
            "used": 0
        }
    }
}


In [5]:
limits = requests.get('https://api.github.com/rate_limit', headers=header)
print(json.dumps(limits.json(), indent=4, sort_keys=True))

{
    "rate": {
        "limit": 5000,
        "remaining": 5000,
        "reset": 1630632398,
        "used": 0
    },
    "resources": {
        "code_scanning_upload": {
            "limit": 500,
            "remaining": 500,
            "reset": 1630632398,
            "used": 0
        },
        "core": {
            "limit": 5000,
            "remaining": 5000,
            "reset": 1630632398,
            "used": 0
        },
        "graphql": {
            "limit": 5000,
            "remaining": 5000,
            "reset": 1630632398,
            "used": 0
        },
        "integration_manifest": {
            "limit": 5000,
            "remaining": 5000,
            "reset": 1630632398,
            "used": 0
        },
        "search": {
            "limit": 30,
            "remaining": 30,
            "reset": 1630628858,
            "used": 0
        },
        "source_import": {
            "limit": 100,
            "remaining": 100,
            "reset": 1630628858,
    

### Búsqueda de repositorios

In [12]:
used_cols = ["id", "name", "full_name", "description", "contributors_url", "archived", "disabled", "stargazers_count",
             "watchers_count", "forks_count", "has_downloads", "has_issues", "has_pages", "has_projects", "has_wiki", 
             "homepage", "html_url", "language", "created_at", "pushed_at", "updated_at", "svn_url", "owner.login"]

In [29]:
def get_df_from_github_calls(response):
    
    response_json = response.json()
    total_count = response_json["total_count"]
    
    print('Procesando URL: {}'.format(response.url))
    
    print('Número de resultados: {}'.format(total_count))
    
    print("Creando dataframe...")

    df = pd.json_normalize(response_json["items"])
    print("Tamaño actual dataframe: {}".format(df.shape[0]))

    while("next" in response.links):
        print("Esperando 7 segundos...")
        time.sleep(wait_time) #Espera de 7 segundos

        print('Procesando URL: {}'.format(response.links["next"]["url"]))
        response = requests.get(response.links["next"]["url"], headers=header)
        response_json = response.json()

        print("Actualizando dataframe...")
        df_next = pd.json_normalize(response_json["items"])
        df = df.append(df_next)
        print("Tamaño actual dataframe: {}".format(df.shape[0]))

    if(df.shape[0] != total_count):
        print("--- [ERROR] Se han almacenado menos resultados de lo esperado \n Número total: {} \n Resultados almacenados: {}"
                                                                                        .format(total_count, df.shape[0]))
        sys.exit(1)
    # Selección solo de las columnas que vamos a utilizar
    df_reducido = df[used_cols]
    
    return df_reducido

In [30]:
def get_df_from_split_calls(date):
    since_date1 = date
    until_date1 = date + timedelta(hours = 12)
    since_date2 = until_date1 + timedelta(seconds = 1)
    until_date2 = until_date1 + timedelta(hours = 11, minutes = 59, seconds = 59)
    
    res_dataframe = pd.DataFrame(columns=used_cols)
    
    query1 = "?per_page=100" + '&q=' + keyword + " created:" + since_date1.strftime("%Y-%m-%dT%H:%M:%S") \
                                                             + ".." + until_date1.strftime("%Y-%m-%dT%H:%M:%S") 
    query2 = "?per_page=100" + '&q=' + keyword + " created:" + since_date2.strftime("%Y-%m-%dT%H:%M:%S") \
                                                             + ".." + until_date2.strftime("%Y-%m-%dT%H:%M:%S") 
    queries = [query1, query2]
    
    for index, query in enumerate(queries, start=1):
        response = requests.get('https://api.github.com/search/repositories' + query, headers=header)
        response_json = response.json()
        
        total_count = response_json["total_count"]
        print("\n --- Tamaño llamada {}: {} ---".format(index, total_count))
        
        print('Procesando URL: {}'.format(response.url))
        print("Creando dataframe...")

        df = pd.json_normalize(response_json["items"])
        print("Tamaño actual dataframe: {}".format(df.shape[0]))

        while("next" in response.links):
            print("Esperando 7 segundos...")
            time.sleep(wait_time) #Espera de 7 segundos

            print('Procesando URL: {}'.format(response.links["next"]["url"]))
            response = requests.get(response.links["next"]["url"], headers=header)
            response_json = response.json()

            print("Actualizando dataframe...")
            df_next = pd.json_normalize(response_json["items"])
            df = df.append(df_next)
            print("Tamaño actual dataframe: {}".format(df.shape[0]))

        if(df.shape[0] != total_count):
            print("--- [ERROR] Se han almacenado menos resultados de lo esperado \n Número total: {} \n Resultados almacenados: {}"
                                                                                            .format(total_count, df.shape[0]))
            sys.exit(1)
        # Selección solo de las columnas que vamos a utilizar
        df_reducido = df[used_cols]

        res_dataframe = res_dataframe.append(df_reducido)
        
    return res_dataframe

In [34]:
keyword = "covid-19"

date = datetime(2020, 3, 2)

limit_date = datetime(2021, 7, 25)

i = 2
while(date <= limit_date):
    print("\n\n -- PROCESANDO FECHA {} --".format(date.strftime("%Y-%m-%d")))
    
    query = "?per_page=100" + '&q=' + keyword + " created:" + date.strftime("%Y-%m-%d")

    response = requests.get('https://api.github.com/search/repositories' + query, headers=header)
    response_json = response.json()
    
    total_count = response_json["total_count"]
    
    if(total_count > 1000):
        print("------- Tamaño mayor a 1000 ({}). Dividimos la llamada... -------".format(total_count))
        df = get_df_from_split_calls(date)
        
    else:
        print("Esperando 5 segundos...")
        time.sleep(5) #Espera de 5 segundos
        df = get_df_from_github_calls(response)

    df.to_csv(r''+keyword+'_'+ str(i) +'.csv', index = False, encoding="utf-8-sig")
        
    date += timedelta(days = 1)
    i += 1



 -- PROCESANDO FECHA 2021-01-04 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-01-04
Número de resultados: 130
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-01-04&page=2
Actualizando dataframe...
Tamaño actual dataframe: 130


 -- PROCESANDO FECHA 2021-01-05 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-01-05
Número de resultados: 157
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-01-05&page=2
Actualizando dataframe...
Tamaño actual dataframe: 157


 -- PROCESANDO FECHA 2021-01-06 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=cov

Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-01-23
Número de resultados: 121
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-01-23&page=2
Actualizando dataframe...
Tamaño actual dataframe: 121


 -- PROCESANDO FECHA 2021-01-24 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-01-24
Número de resultados: 144
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-01-24&page=2
Actualizando dataframe...
Tamaño actual dataframe: 144


 -- PROCESANDO FECHA 2021-01-25 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-01-25
Número de 

Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-02-12
Número de resultados: 95
Creando dataframe...
Tamaño actual dataframe: 95


 -- PROCESANDO FECHA 2021-02-13 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-02-13
Número de resultados: 103
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-02-13&page=2
Actualizando dataframe...
Tamaño actual dataframe: 103


 -- PROCESANDO FECHA 2021-02-14 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-02-14
Número de resultados: 110
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-02-1

Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-03-04&page=2
Actualizando dataframe...
Tamaño actual dataframe: 131


 -- PROCESANDO FECHA 2021-03-05 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-03-05
Número de resultados: 74
Creando dataframe...
Tamaño actual dataframe: 74


 -- PROCESANDO FECHA 2021-03-06 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-03-06
Número de resultados: 114
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-03-06&page=2
Actualizando dataframe...
Tamaño actual dataframe: 114


 -- PROCESANDO FECHA 2021-03-07 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-03-07

Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-03-26&page=2
Actualizando dataframe...
Tamaño actual dataframe: 114


 -- PROCESANDO FECHA 2021-03-27 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-03-27
Número de resultados: 96
Creando dataframe...
Tamaño actual dataframe: 96


 -- PROCESANDO FECHA 2021-03-28 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-03-28
Número de resultados: 97
Creando dataframe...
Tamaño actual dataframe: 97


 -- PROCESANDO FECHA 2021-03-29 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-03-29
Número de resultados: 115
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%

Actualizando dataframe...
Tamaño actual dataframe: 115


 -- PROCESANDO FECHA 2021-04-17 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-04-17
Número de resultados: 100
Creando dataframe...
Tamaño actual dataframe: 100


 -- PROCESANDO FECHA 2021-04-18 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-04-18
Número de resultados: 123
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-04-18&page=2
Actualizando dataframe...
Tamaño actual dataframe: 123


 -- PROCESANDO FECHA 2021-04-19 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-04-19
Número de resultados: 128
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesan

Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-05-06&page=2
Actualizando dataframe...
Tamaño actual dataframe: 157


 -- PROCESANDO FECHA 2021-05-07 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-05-07
Número de resultados: 166
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-05-07&page=2
Actualizando dataframe...
Tamaño actual dataframe: 166


 -- PROCESANDO FECHA 2021-05-08 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-05-08
Número de resultados: 139
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-05-08&page=2
Actualizando dataframe...
T

Actualizando dataframe...
Tamaño actual dataframe: 164


 -- PROCESANDO FECHA 2021-05-26 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-05-26
Número de resultados: 131
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-05-26&page=2
Actualizando dataframe...
Tamaño actual dataframe: 131


 -- PROCESANDO FECHA 2021-05-27 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-05-27
Número de resultados: 163
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-05-27&page=2
Actualizando dataframe...
Tamaño actual dataframe: 163


 -- PROCESANDO FECHA 2021-05-28 --
Esperando 5 segundos...
Procesando URL: https:

Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-06-14
Número de resultados: 143
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-06-14&page=2
Actualizando dataframe...
Tamaño actual dataframe: 143


 -- PROCESANDO FECHA 2021-06-15 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-06-15
Número de resultados: 123
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-06-15&page=2
Actualizando dataframe...
Tamaño actual dataframe: 123


 -- PROCESANDO FECHA 2021-06-16 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-06-16
Número de 

Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-07-03
Número de resultados: 121
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-07-03&page=2
Actualizando dataframe...
Tamaño actual dataframe: 121


 -- PROCESANDO FECHA 2021-07-04 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-07-04
Número de resultados: 126
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-07-04&page=2
Actualizando dataframe...
Tamaño actual dataframe: 126


 -- PROCESANDO FECHA 2021-07-05 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-07-05
Número de resultados: 111
Creando 

Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-07-22&page=2
Actualizando dataframe...
Tamaño actual dataframe: 109


 -- PROCESANDO FECHA 2021-07-23 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-07-23
Número de resultados: 112
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-07-23&page=2
Actualizando dataframe...
Tamaño actual dataframe: 112


 -- PROCESANDO FECHA 2021-07-24 --
Esperando 5 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19%20created:2021-07-24
Número de resultados: 124
Creando dataframe...
Tamaño actual dataframe: 100
Esperando 7 segundos...
Procesando URL: https://api.github.com/search/repositories?per_page=100&q=covid-19+created%3A2021-07-24&page=2
Actualizando dataframe...
T

----

### Unión de ficheros CSV

In [1]:
import os
from glob import glob
import pandas as pd

path = "/coronavirus/"

In [10]:
files = glob("coronavirus/coronavirus_*.csv")
files

['coronavirus\\coronavirus_1.csv',
 'coronavirus\\coronavirus_10.csv',
 'coronavirus\\coronavirus_100.csv',
 'coronavirus\\coronavirus_101.csv',
 'coronavirus\\coronavirus_102.csv',
 'coronavirus\\coronavirus_103.csv',
 'coronavirus\\coronavirus_104.csv',
 'coronavirus\\coronavirus_105.csv',
 'coronavirus\\coronavirus_106.csv',
 'coronavirus\\coronavirus_107.csv',
 'coronavirus\\coronavirus_108.csv',
 'coronavirus\\coronavirus_109.csv',
 'coronavirus\\coronavirus_11.csv',
 'coronavirus\\coronavirus_110.csv',
 'coronavirus\\coronavirus_111.csv',
 'coronavirus\\coronavirus_112.csv',
 'coronavirus\\coronavirus_113.csv',
 'coronavirus\\coronavirus_114.csv',
 'coronavirus\\coronavirus_115.csv',
 'coronavirus\\coronavirus_116.csv',
 'coronavirus\\coronavirus_117.csv',
 'coronavirus\\coronavirus_118.csv',
 'coronavirus\\coronavirus_119.csv',
 'coronavirus\\coronavirus_12.csv',
 'coronavirus\\coronavirus_120.csv',
 'coronavirus\\coronavirus_121.csv',
 'coronavirus\\coronavirus_122.csv',
 'coro

In [11]:
df = pd.concat(map(pd.read_csv, files), ignore_index=True)

In [12]:
df

id                      name  \
0      238316428                  COVID-19   
1      235374822                  COVID-19   
2      239777191               coronavirus   
3      237129709               coronavirus   
4      234936988                      ncov   
...          ...                       ...   
15237  270364345      covid-berlin-scraper   
15238  270337965                   Covid19   
15239  270412711          CovidDataParsers   
15240  270428942             COVID-Compare   
15241  270194719  LUSIP-Sentiment-Analysis   

                                  full_name  \
0                   CSSEGISandData/COVID-19   
1                    midas-network/COVID-19   
2                   RamiKrispin/coronavirus   
3                 FoldingAtHome/coronavirus   
4                           nextstrain/ncov   
...                                     ...   
15237     jakubvalenta/covid-berlin-scraper   
15238                   Fgazzelloni/Covid19   
15239            tudorpop9/CovidDataParsers   
15240             Ashwins9001/COVID-Compare   
15241  tanmayvijay/LUSIP-Sentiment-Analysis   

                                             description  \
0      Novel Coronavirus (COVID-19) Cases, provided b...   
1                      2019 novel coronavirus repository   
2                                The coronavirus dataset   
3                          Folding@home COVID-19 efforts   
4      Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                  ...   
15237  Download coronavirus data from the official pr...   
15238          This repository is about Covid19 Outbreak   
15239  Programs used to refine the raw data from http...   
15240  Find keyword trends (Using k-means and gaussia...   
15241  This repository contains all code and work fil...   

                                        contributors_url  archived  disabled  \
0      https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1      https://api.github.com/repos/midas-network/COV...     False     False   
2      https://api.github.com/repos/RamiKrispin/coron...     False     False   
3      https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4      https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                  ...       ...       ...   
15237  https://api.github.com/repos/jakubvalenta/covi...     False     False   
15238  https://api.github.com/repos/Fgazzelloni/Covid...     False     False   
15239  https://api.github.com/repos/tudorpop9/CovidDa...     False     False   
15240  https://api.github.com/repos/Ashwins9001/COVID...     False     False   
15241  https://api.github.com/repos/tanmayvijay/LUSIP...     False     False   

       stargazers_count  watchers_count  forks_count  ...  has_wiki  \
0                 27211           27211        17432  ...      True   
1                   642             642          221  ...      True   
2                   394             394          175  ...      True   
3                  1115            1115           87  ...      True   
4                  1208            1208          343  ...      True   
...                 ...             ...          ...  ...       ...   
15237                 1               1            0  ...      True   
15238                 0               0            0  ...      True   
15239                 0               0            0  ...      True   
15240                 0               0            0  ...      True   
15241                 0               0            1  ...      True   

                                                homepage  \
0      https://systems.jhu.edu/research/public-health...   
1                                                    NaN   
2             https://ramikrispin.github.io/coronavirus/   
3                              https://foldingathome.org   
4                            https://nextstrain.org/ncov   
.

In [13]:
df.to_csv(r'coronavirus_merged.csv', index = False, encoding="utf-8-sig")

### Unión de los cuatro datasets

In [16]:
df_completo = pd.DataFrame(columns=used_cols)

coronavirus = pd.read_csv('coronavirus_merged.csv')
covid = pd.read_csv('covid_merged.csv')
covid19 = pd.read_csv('covid19_merged.csv')
covid_19 = pd.read_csv('covid-19_merged.csv')

dataframes = [coronavirus, covid, covid19, covid_19]

In [17]:
for df in dataframes:
    df_completo = df_completo.append(df)

In [18]:
df_completo

id                          name  \
0       238316428                      COVID-19   
1       235374822                      COVID-19   
2       239777191                   coronavirus   
3       237129709                   coronavirus   
4       234936988                          ncov   
...           ...                           ...   
110986  270364345          covid-berlin-scraper   
110987  270393880  PAP_V20_Covid_SocialAnalysis   
110988  270466209                         ADLTS   
110989  270379783                        covidn   
110990  270443985                 Check-InToday   

                                           full_name  \
0                            CSSEGISandData/COVID-19   
1                             midas-network/COVID-19   
2                            RamiKrispin/coronavirus   
3                          FoldingAtHome/coronavirus   
4                                    nextstrain/ncov   
...                                              ...   
110986             jakubvalenta/covid-berlin-scraper   
110987  AraceliCastillo/PAP_V20_Covid_SocialAnalysis   
110988                         trevinofernando/ADLTS   
110989                                  aiosk/covidn   
110990                       BlueWing0/Check-InToday   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
110986  Download coronavirus data from the official pr...   
110987  En este PAP, se busca desarrollar un dashboard...   
110988  A Unity Simulation for the Automated Drone Las...   
110989  covid19 cases both national and provinces in i...   
110990  What's one thing we as a community miss during...   

                                         contributors_url archived disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...    False    False   
1       https://api.github.com/repos/midas-network/COV...    False    False   
2       https://api.github.com/repos/RamiKrispin/coron...    False    False   
3       https://api.github.com/repos/FoldingAtHome/cor...    False    False   
4       https://api.github.com/repos/nextstrain/ncov/c...    False    False   
...                                                   ...      ...      ...   
110986  https://api.github.com/repos/jakubvalenta/covi...    False    False   
110987  https://api.github.com/repos/AraceliCastillo/P...    False    False   
110988  https://api.github.com/repos/trevinofernando/A...    False    False   
110989  https://api.github.com/repos/aiosk/covidn/cont...    False    False   
110990  https://api.github.com/repos/BlueWing0/Check-I...    False    False   

       stargazers_count watchers_count forks_count  ... has_wiki  \
0                 27211          27211       17432  ...     True   
1                   642            642         221  ...     True   
2                   394            394         175  ...     True   
3                  1115           1115          87  ...     True   
4                  1208           1208         343  ...     True   
...                 ...            ...         ...  ...      ...   
110986                1              1           0  ...     True   
110987                0              0           0  ...     True   
110988                0              0           0  ...     True   
110989                0              0           0  ...     True   
110990                0              0           0  ...     True   

                                                 homepage  \
0       https://systems.jhu.edu/research/public-health...   
1                                                     NaN   
2              https://ramikrispin.github.io/co

In [34]:
df_completo.shape[0]

337195

### Limpieza y preprocesamiento

Eliminamos las filas duplicadas.

In [28]:
print(df_completo.duplicated(['id']).sum())

159125


In [32]:
df_deduplicado = df_completo.drop_duplicates(subset=['id'])

In [33]:
df_deduplicado

id                             name  \
0       238316428                         COVID-19   
1       235374822                         COVID-19   
2       239777191                      coronavirus   
3       237129709                      coronavirus   
4       234936988                             ncov   
...           ...                              ...   
110402  269527538  OpenWeatherMap-concat-histories   
110652  270034436                    mzansi_corona   
110656  269906994              face-mask-detection   
110661  270013759                         frontend   
110662  270006438                          backend   

                                     full_name  \
0                      CSSEGISandData/COVID-19   
1                       midas-network/COVID-19   
2                      RamiKrispin/coronavirus   
3                    FoldingAtHome/coronavirus   
4                              nextstrain/ncov   
...                                        ...   
110402  ALT-F1/OpenWeatherMap-concat-histories   
110652             marvinIsSacul/mzansi_corona   
110656      jahnavi-prasad/face-mask-detection   
110661                        Tackode/frontend   
110662                         Tackode/backend   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
110402  Concatenate histories weather data collected b...   
110652  Flutter app about South Africa's Corona Virus ...   
110656  Simple project to detect if a person is wearin...   
110661                               Frontend for Tackode   
110662                                Backend for Tackode   

                                         contributors_url archived disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...    False    False   
1       https://api.github.com/repos/midas-network/COV...    False    False   
2       https://api.github.com/repos/RamiKrispin/coron...    False    False   
3       https://api.github.com/repos/FoldingAtHome/cor...    False    False   
4       https://api.github.com/repos/nextstrain/ncov/c...    False    False   
...                                                   ...      ...      ...   
110402  https://api.github.com/repos/ALT-F1/OpenWeathe...    False    False   
110652  https://api.github.com/repos/marvinIsSacul/mza...    False    False   
110656  https://api.github.com/repos/jahnavi-prasad/fa...    False    False   
110661  https://api.github.com/repos/Tackode/frontend/...    False    False   
110662  https://api.github.com/repos/Tackode/backend/c...    False    False   

       stargazers_count watchers_count forks_count  ... has_wiki  \
0                 27211          27211       17432  ...     True   
1                   642            642         221  ...     True   
2                   394            394         175  ...     True   
3                  1115           1115          87  ...     True   
4                  1208           1208         343  ...     True   
...                 ...            ...         ...  ...      ...   
110402                1              1           0  ...     True   
110652                0              0           0  ...     True   
110656                6              6           7  ...     True   
110661                0              0           0  ...     True   
110662                0              0           0  ...     True   

                                                 homepage  \
0       https://systems.jhu.edu/research/public-health...   
1                                                     NaN   
2              https://ramikrispin.github.io/coronavirus/   
3                     

In [35]:
# Exportamos a CSV para no perder el progreso
df_deduplicado.to_csv(r'df_deduplicado.csv', index = False, encoding="utf-8-sig")

Eliminamos la columna license, obtenida por error y sin haberse parseado correctamente desde JSON a tabla por ser objeto:

In [126]:
df = pd.read_csv('df_deduplicado.csv')

df_sin_license = df.drop(columns=['license'])

Finalmente lo exportamos de nuevo:

In [127]:
df_sin_license.to_csv(r'df_repositorios.csv', index = False, encoding="utf-8-sig")

------

## Filtrado

In [10]:
df = pd.read_csv('df_repositorios.csv')
df

id                             name  \
0       238316428                         COVID-19   
1       235374822                         COVID-19   
2       239777191                      coronavirus   
3       237129709                      coronavirus   
4       234936988                             ncov   
...           ...                              ...   
178065  269527538  OpenWeatherMap-concat-histories   
178066  270034436                    mzansi_corona   
178067  269906994              face-mask-detection   
178068  270013759                         frontend   
178069  270006438                          backend   

                                     full_name  \
0                      CSSEGISandData/COVID-19   
1                       midas-network/COVID-19   
2                      RamiKrispin/coronavirus   
3                    FoldingAtHome/coronavirus   
4                              nextstrain/ncov   
...                                        ...   
178065  ALT-F1/OpenWeatherMap-concat-histories   
178066             marvinIsSacul/mzansi_corona   
178067      jahnavi-prasad/face-mask-detection   
178068                        Tackode/frontend   
178069                         Tackode/backend   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178065  Concatenate histories weather data collected b...   
178066  Flutter app about South Africa's Corona Virus ...   
178067  Simple project to detect if a person is wearin...   
178068                               Frontend for Tackode   
178069                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178065  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178066  https://api.github.com/repos/marvinIsSacul/mza...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   
178068  https://api.github.com/repos/Tackode/frontend/...     False     False   
178069  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178065                 1               1            0  ...          True   
178066                 0               0            0  ...          True   
178067                 6               6            7  ...          True   
178068                 0               0            0  ...          True   
178069                 0               0            0  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1   

Con la librería pandasgui podemos visualizar mejor los dataframes de Pandas:

In [3]:
from pandasgui import show
show(df)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178070 entries, 0 to 178069
Data columns (total 23 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   id                178070 non-null  int64 
 1   name              178070 non-null  object
 2   full_name         178070 non-null  object
 3   description       100021 non-null  object
 4   contributors_url  178070 non-null  object
 5   archived          178070 non-null  bool  
 6   disabled          178070 non-null  bool  
 7   stargazers_count  178070 non-null  int64 
 8   watchers_count    178070 non-null  int64 
 9   forks_count       178070 non-null  int64 
 10  has_downloads     178070 non-null  bool  
 11  has_issues        178070 non-null  bool  
 12  has_pages         178070 non-null  bool  
 13  has_projects      178070 non-null  bool  
 14  has_wiki          178070 non-null  bool  
 15  homepage          15382 non-null   object
 16  html_url          178070 non-null  obj

## Palabras relacionadas

In [19]:
related_name_words = ["corona", "coronavirus", "covid", "covid19", "covid-19", "sars-cov-2", "sars-cov-2", "sars-cov", "cov", 
                 "ncov", "ncov2019", "ncov19", "19ncov", "19-ncov", "2019ncov", "2019-ncov", "virus", "pandemic", "epidemic",
                    "新冠病毒", "新型冠状病毒"]
related_description_words = ["corona", "coronavirus", "covid", "covid19", "covid-19", "sars-cov-2", "sars-cov-2", "sars-cov", 
                             "cov", "ncov", "ncov2019", "ncov19", "19ncov", "19-ncov", "2019ncov", "2019-ncov", "virus", 
                             "pandemic", "epidemic", "新冠病毒", "新型冠状病毒", "cases", "contagios" "reported", "medical", 
                             "infections", "infection", "lockdown", "viral", "mask", "vaccine", "disease", "deaths", 
                             "pneumonia"]

In [20]:
pattern_name = "(?i)" + '|'.join(related_name_words)
pattern_description = "(?i)" + '|'.join(related_description_words)
pattern_description

'(?i)corona|coronavirus|covid|covid19|covid-19|sars-cov-2|sars-cov-2|sars-cov|cov|ncov|ncov2019|ncov19|19ncov|19-ncov|2019ncov|2019-ncov|virus|pandemic|epidemic|新冠病毒|新型冠状病毒|cases|contagiosreported|medical|infections|infection|lockdown|viral|mask|vaccine|disease|deaths|pneumonia'

In [9]:
df = pd.read_csv('repositorios_primer_filtrado.csv')
df

id                             name  \
0       238316428                         COVID-19   
1       235374822                         COVID-19   
2       239777191                      coronavirus   
3       237129709                      coronavirus   
4       234936988                             ncov   
...           ...                              ...   
178038  269527538  OpenWeatherMap-concat-histories   
178039  270034436                    mzansi_corona   
178040  269906994              face-mask-detection   
178041  270013759                         frontend   
178042  270006438                          backend   

                                     full_name  \
0                      CSSEGISandData/COVID-19   
1                       midas-network/COVID-19   
2                      RamiKrispin/coronavirus   
3                    FoldingAtHome/coronavirus   
4                              nextstrain/ncov   
...                                        ...   
178038  ALT-F1/OpenWeatherMap-concat-histories   
178039             marvinIsSacul/mzansi_corona   
178040      jahnavi-prasad/face-mask-detection   
178041                        Tackode/frontend   
178042                         Tackode/backend   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178038  Concatenate histories weather data collected b...   
178039  Flutter app about South Africa's Corona Virus ...   
178040  Simple project to detect if a person is wearin...   
178041                               Frontend for Tackode   
178042                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178038  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178039  https://api.github.com/repos/marvinIsSacul/mza...     False     False   
178040  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   
178041  https://api.github.com/repos/Tackode/frontend/...     False     False   
178042  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178038                 1               1            0  ...          True   
178039                 0               0            0  ...          True   
178040                 6               6            7  ...          True   
178041                 0               0            0  ...          True   
178042                 0               0            0  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1   

### Comprobación solo en el nombre:

Dataframe resultante con columna *full_name* conteniendo el patrón:

In [7]:
df_in_name_boolean = df.full_name.str.contains(pattern_name)
df_in_name_boolean

0          True
1          True
2          True
3          True
4          True
          ...  
178065    False
178066     True
178067    False
178068    False
178069    False
Name: full_name, Length: 178070, dtype: bool

In [8]:
df_in_name_boolean.sum()

159157

In [9]:
df_in_name = df[df_in_name_boolean]
df_in_name

id                 name                        full_name  \
0       238316428             COVID-19          CSSEGISandData/COVID-19   
1       235374822             COVID-19           midas-network/COVID-19   
2       239777191          coronavirus          RamiKrispin/coronavirus   
3       237129709          coronavirus        FoldingAtHome/coronavirus   
4       234936988                 ncov                  nextstrain/ncov   
...           ...                  ...                              ...   
178054  268148998  Epidemics-Modelling  pierpaolo28/Epidemics-Modelling   
178056  268314248                   UI                    CovidToday/UI   
178061  268770101             coroname                mariabnd/coroname   
178064  269601203      CoronaDashboard            StefH/CoronaDashboard   
178066  270034436        mzansi_corona      marvinIsSacul/mzansi_corona   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178054  Modelling and tracking of epidemics data analy...   
178056                                                NaN   
178061                                                NaN   
178064  Een Corona Dashboard gebaseerd op cijfers van ...   
178066  Flutter app about South Africa's Corona Virus ...   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178054  https://api.github.com/repos/pierpaolo28/Epide...     False     False   
178056  https://api.github.com/repos/CovidToday/UI/con...     False     False   
178061  https://api.github.com/repos/mariabnd/coroname...     False     False   
178064  https://api.github.com/repos/StefH/CoronaDashb...     False     False   
178066  https://api.github.com/repos/marvinIsSacul/mza...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178054                 1               1            0  ...          True   
178056                 0               0            0  ...          True   
178061                 0               0            0  ...          True   
178064                 1               1            0  ...          True   
178066                 0               0            0  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1           True                                                NaN   
2           True         https://ramikrispin.github.io/coronavirus/   
3           True                          https://foldingathome.org   
4           True                        https://nextstrain.org/ncov   
...          ...                                                ...  

**159.157** repositorios.

### Comprobación solo en la descripción:

Comprobamos previamente si hay repositorios con la descripción vacía:

In [10]:
df["description"].isnull().sum()

78049

Existen 78049 repositorios sin descripción. Lo tendremos en cuenta a continuación.

In [21]:
df_in_description_boolean = df.description.str.contains(pattern_description)
df_in_description_boolean

0          True
1          True
2          True
3          True
4          True
          ...  
178065    False
178066     True
178067     True
178068    False
178069    False
Name: description, Length: 178070, dtype: object

De aquí saldrán 78049 valores que no se corresponderán a False ni True, por lo que no nos dejará filtrar el dataframe. Los convertimos a False:

In [12]:
print(df_in_description_boolean.isnull().sum())

78049


In [13]:
df_in_description_boolean = df_in_description_boolean.fillna(False)

#Comprobamos si tiene valores nulos
print(df_in_description_boolean.isnull().sum())

0


Contamos cuantos repositorios tienen las palabras relacionadas en la descripción:

In [14]:
df_in_description_boolean.sum()

84100

In [15]:
df_in_description = df[df_in_description_boolean]
df_in_description

id                          name  \
0       238316428                      COVID-19   
1       235374822                      COVID-19   
2       239777191                   coronavirus   
3       237129709                   coronavirus   
4       234936988                          ncov   
...           ...                           ...   
178051  267858096  face_mask_detection_openvino   
178054  268148998           Epidemics-Modelling   
178064  269601203               CoronaDashboard   
178066  270034436                 mzansi_corona   
178067  269906994           face-mask-detection   

                                   full_name  \
0                    CSSEGISandData/COVID-19   
1                     midas-network/COVID-19   
2                    RamiKrispin/coronavirus   
3                  FoldingAtHome/coronavirus   
4                            nextstrain/ncov   
...                                      ...   
178051  mmphego/face_mask_detection_openvino   
178054       pierpaolo28/Epidemics-Modelling   
178064                 StefH/CoronaDashboard   
178066           marvinIsSacul/mzansi_corona   
178067    jahnavi-prasad/face-mask-detection   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178051  Detect faces and determine whether people are ...   
178054  Modelling and tracking of epidemics data analy...   
178064  Een Corona Dashboard gebaseerd op cijfers van ...   
178066  Flutter app about South Africa's Corona Virus ...   
178067  Simple project to detect if a person is wearin...   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178051  https://api.github.com/repos/mmphego/face_mask...     False     False   
178054  https://api.github.com/repos/pierpaolo28/Epide...     False     False   
178064  https://api.github.com/repos/StefH/CoronaDashb...     False     False   
178066  https://api.github.com/repos/marvinIsSacul/mza...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178051                35              35           11  ...          True   
178054                 1               1            0  ...          True   
178064                 1               1            0  ...          True   
178066                 0               0            0  ...          True   
178067                 6               6            7  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1           True                                                

**84.100** repositorios.

### En el nombre y no la descripción:

In [16]:
#En el nombre:
df_in_name_not_in_description = df.full_name.str.contains(pattern_name)
df_in_name_not_in_description

0          True
1          True
2          True
3          True
4          True
          ...  
178065    False
178066     True
178067    False
178068    False
178069    False
Name: full_name, Length: 178070, dtype: bool

In [17]:
df_in_name_not_in_description = df[df_in_name_not_in_description]
df_in_name_not_in_description

id                 name                        full_name  \
0       238316428             COVID-19          CSSEGISandData/COVID-19   
1       235374822             COVID-19           midas-network/COVID-19   
2       239777191          coronavirus          RamiKrispin/coronavirus   
3       237129709          coronavirus        FoldingAtHome/coronavirus   
4       234936988                 ncov                  nextstrain/ncov   
...           ...                  ...                              ...   
178054  268148998  Epidemics-Modelling  pierpaolo28/Epidemics-Modelling   
178056  268314248                   UI                    CovidToday/UI   
178061  268770101             coroname                mariabnd/coroname   
178064  269601203      CoronaDashboard            StefH/CoronaDashboard   
178066  270034436        mzansi_corona      marvinIsSacul/mzansi_corona   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178054  Modelling and tracking of epidemics data analy...   
178056                                                NaN   
178061                                                NaN   
178064  Een Corona Dashboard gebaseerd op cijfers van ...   
178066  Flutter app about South Africa's Corona Virus ...   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178054  https://api.github.com/repos/pierpaolo28/Epide...     False     False   
178056  https://api.github.com/repos/CovidToday/UI/con...     False     False   
178061  https://api.github.com/repos/mariabnd/coroname...     False     False   
178064  https://api.github.com/repos/StefH/CoronaDashb...     False     False   
178066  https://api.github.com/repos/marvinIsSacul/mza...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178054                 1               1            0  ...          True   
178056                 0               0            0  ...          True   
178061                 0               0            0  ...          True   
178064                 1               1            0  ...          True   
178066                 0               0            0  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1           True                                                NaN   
2           True         https://ramikrispin.github.io/coronavirus/   
3           True                          https://foldingathome.org   
4           True                        https://nextstrain.org/ncov   
...          ...                                                ...  

No en la descripción:

In [18]:
df_in_name_not_in_description_boolean = df.description.str.contains(pattern_description) == False
df_in_name_not_in_description_boolean 

0         False
1         False
2         False
3         False
4         False
          ...  
178065     True
178066    False
178067    False
178068     True
178069     True
Name: description, Length: 178070, dtype: bool

In [19]:
df_in_name_not_in_description = df_in_name_not_in_description[df_in_name_not_in_description_boolean]
df_in_name_not_in_description

<ipython-input-19-efb1122a8ec8>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_in_name_not_in_description = df_in_name_not_in_description[df_in_name_not_in_description_boolean]


id                         name  \
56      238121123                  coronavirus   
70      238965247                  coronavirus   
86      238643080  Noval-Coronavirus-763-Cases   
148     239239938        coronavirus-2019-nCov   
158     242778847                  Here-Corona   
...           ...                          ...   
177930  259285155           Novel-Corona-India   
177956  260912128        Covid-19-info-Counter   
177958  261163082             Project-COVgh-V1   
177991  264028112                 covid-19-app   
178031  266802091          REIDCoronaHackathon   

                                     full_name  \
56                        bjwa2020/coronavirus   
70                     weimeilin79/coronavirus   
86      839-Studio/Noval-Coronavirus-763-Cases   
148             C0D4-101/coronavirus-2019-nCov   
158                       SoonGwan/Here-Corona   
...                                        ...   
177930         ni3mumbaikar/Novel-Corona-India   
177956         KhanOmair/Covid-19-info-Counter   
177958            E-B-Manohar/Project-COVgh-V1   
177991               leoalcantara/covid-19-app   
178031     vinnik-dmitry07/REIDCoronaHackathon   

                                              description  \
56                    新冠疫情小区分布数据（数据来自各城市卫健委等官方微信公众号和官方网站）   
70                                Camel K Serverless Demo   
86                 763例冠状病毒确诊患者的详细情况，包括出行轨迹、发病就诊时间、人传人情况。   
148          Data Extracts from World Health Organization   
158     국내, 전세계 코로나 현황을 한눈에 알아 볼 수 있으며, 여러 정보를 제공하는 웹 ...   
...                                                   ...   
177930  This Project is good example of web scraping u...   
177956  This is a Project I created by me while I was ...   
177958  Sickness Detection with 80% Val Accuracy. Trai...   
177991                  Aplicação feita com ReactJS e PWA   
178031  Multiple cameras recognition of prolonged inte...   

                                         contributors_url  archived  disabled  \
56      https://api.github.com/repos/bjwa2020/coronavi...     False     False   
70      https://api.github.com/repos/weimeilin79/coron...     False     False   
86      https://api.github.com/repos/839-Studio/Noval-...     False     False   
148     https://api.github.com/repos/C0D4-101/coronavi...     False     False   
158     https://api.github.com/repos/SoonGwan/Here-Cor...     False     False   
...                                                   ...       ...       ...   
177930  https://api.github.com/repos/ni3mumbaikar/Nove...     False     False   
177956  https://api.github.com/repos/KhanOmair/Covid-1...     False     False   
177958  https://api.github.com/repos/E-B-Manohar/Proje...     False     False   
177991  https://api.github.com/repos/leoalcantara/covi...     False     False   
178031  https://api.github.com/repos/vinnik-dmitry07/R...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
56                    23              23            3  ...          True   
70                     5               5            4  ...          True   
86                    11              11            4  ...          True   
148                    8               8            1  ...          True   
158                    8               8            3  ...          True   
...                  ...             ...          ...  ...           ...   
177930                 1               1            2  ...          True   
177956                 0               0            0  ...          True   
177958                 7               7            3  ...          True   
177991                 0               0            0  ...          True   
178031                 0               0            0  ...          True   

        has_wiki              homepage  \
56          True  https://www.gubi.io/   
70          True                   NaN   
86          True                   NaN   
148         True          

**14.714** repositorios.

### No en el nombre pero sí en la descripción:

In [20]:
df_not_in_name_but_in_description = df.full_name.str.contains(pattern_name) == False
df_not_in_name_but_in_description

0         False
1         False
2         False
3         False
4         False
          ...  
178065     True
178066    False
178067     True
178068     True
178069     True
Name: full_name, Length: 178070, dtype: bool

In [21]:
df_not_in_name_but_in_description = df[df_not_in_name_but_in_description]
df_not_in_name_but_in_description

id                              name  \
40      237221585                        gatsby-map   
41      236218942                              cido   
64      237385601  Getting-Things-Done-with-Pytorch   
67      236146885                         pneumonia   
72      229427465                Hentai-discord-bot   
...           ...                               ...   
178063  269479371                           jupyter   
178065  269527538   OpenWeatherMap-concat-histories   
178067  269906994               face-mask-detection   
178068  270013759                          frontend   
178069  270006438                           backend   

                                          full_name  \
40                              elinlutz/gatsby-map   
41                               CIDO-ontology/cido   
64      curiousily/Getting-Things-Done-with-Pytorch   
67                                lispczz/pneumonia   
72                     Eddy-Arch/Hentai-discord-bot   
...                                             ...   
178063                                kclhi/jupyter   
178065       ALT-F1/OpenWeatherMap-concat-histories   
178067           jahnavi-prasad/face-mask-detection   
178068                             Tackode/frontend   
178069                              Tackode/backend   

                                              description  \
40      Mapping the coronavirus in react, gatsby.js an...   
41          CIDO: Coronavirus Infectious Disease Ontology   
64      Jupyter Notebook tutorials on solving real-wor...   
67                                       中国新型冠状病毒肺炎地级市疫情图   
72      A NSFW hentai discord bot with extra functiona...   
...                                                   ...   
178063           :whale2: JupyterHub Docker configuration   
178065  Concatenate histories weather data collected b...   
178067  Simple project to detect if a person is wearin...   
178068                               Frontend for Tackode   
178069                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
40      https://api.github.com/repos/elinlutz/gatsby-m...     False     False   
41      https://api.github.com/repos/CIDO-ontology/cid...     False     False   
64      https://api.github.com/repos/curiousily/Gettin...     False     False   
67      https://api.github.com/repos/lispczz/pneumonia...     False     False   
72      https://api.github.com/repos/Eddy-Arch/Hentai-...     False     False   
...                                                   ...       ...       ...   
178063  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
178065  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   
178068  https://api.github.com/repos/Tackode/frontend/...     False     False   
178069  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
40                    31              31           12  ...          True   
41                    13              13            9  ...          True   
64                   957             957          300  ...          True   
67                   356             356          100  ...          True   
72                    21              21           12  ...          True   
...                  ...             ...          ...  ...           ...   
178063                 2               2            0  ...          True   
178065                 1               1            0  ...          True   
178067                 6               6            7  ...          True   
178068                 0               0            0  ...          True   
178069                 0               0            0  ...          True   

        has_wiki                              homepage  \
40          True

In [22]:
df_not_in_name_but_in_description_boolean = df.description.str.contains(pattern_description)
df_not_in_name_but_in_description_boolean 

0          True
1          True
2          True
3          True
4          True
          ...  
178065    False
178066     True
178067     True
178068    False
178069    False
Name: description, Length: 178070, dtype: object

In [23]:
df_not_in_name_but_in_description_boolean = df_not_in_name_but_in_description_boolean.fillna(False)

In [24]:
df_not_in_name_but_in_description = df_not_in_name_but_in_description[df_not_in_name_but_in_description_boolean]
df_not_in_name_but_in_description

<ipython-input-24-fa5b93223eed>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_not_in_name_but_in_description = df_not_in_name_but_in_description[df_not_in_name_but_in_description_boolean]


id                              name  \
40      237221585                        gatsby-map   
41      236218942                              cido   
64      237385601  Getting-Things-Done-with-Pytorch   
67      236146885                         pneumonia   
72      229427465                Hentai-discord-bot   
...           ...                               ...   
178037  267352452                    steam-lockdown   
178047  267575087                Smart-Food-Storage   
178050  246130172                         Airplanes   
178051  267858096      face_mask_detection_openvino   
178067  269906994               face-mask-detection   

                                          full_name  \
40                              elinlutz/gatsby-map   
41                               CIDO-ontology/cido   
64      curiousily/Getting-Things-Done-with-Pytorch   
67                                lispczz/pneumonia   
72                     Eddy-Arch/Hentai-discord-bot   
...                                             ...   
178037             digital-wellbeing/steam-lockdown   
178047                m-boutaleb/Smart-Food-Storage   
178050                          cgettings/Airplanes   
178051         mmphego/face_mask_detection_openvino   
178067           jahnavi-prasad/face-mask-detection   

                                              description  \
40      Mapping the coronavirus in react, gatsby.js an...   
41          CIDO: Coronavirus Infectious Disease Ontology   
64      Jupyter Notebook tutorials on solving real-wor...   
67                                       中国新型冠状病毒肺炎地级市疫情图   
72      A NSFW hentai discord bot with extra functiona...   
...                                                   ...   
178037  How has gaming changed during lockdown? Analys...   
178047  An intelligent application (very useful during...   
178050  Visualizing flights into LGA at the start of t...   
178051  Detect faces and determine whether people are ...   
178067  Simple project to detect if a person is wearin...   

                                         contributors_url  archived  disabled  \
40      https://api.github.com/repos/elinlutz/gatsby-m...     False     False   
41      https://api.github.com/repos/CIDO-ontology/cid...     False     False   
64      https://api.github.com/repos/curiousily/Gettin...     False     False   
67      https://api.github.com/repos/lispczz/pneumonia...     False     False   
72      https://api.github.com/repos/Eddy-Arch/Hentai-...     False     False   
...                                                   ...       ...       ...   
178037  https://api.github.com/repos/digital-wellbeing...     False     False   
178047  https://api.github.com/repos/m-boutaleb/Smart-...     False     False   
178050  https://api.github.com/repos/cgettings/Airplan...     False     False   
178051  https://api.github.com/repos/mmphego/face_mask...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
40                    31              31           12  ...          True   
41                    13              13            9  ...          True   
64                   957             957          300  ...          True   
67                   356             356          100  ...          True   
72                    21              21           12  ...          True   
...                  ...             ...          ...  ...           ...   
178037                 0               0            0  ...          True   
178047                 0               0            0  ...          True   
178050                 0               0            0  ...          True   
178051                35              35           11  ...          True   
178067                 6               6            7  ...          True   

        has_wiki                                           homepage  \
40 

**17.566** repositorios.

### En el nombre y en la descripción:

In [25]:
df_in_name_and_description_boolean = df.full_name.str.contains(pattern_name) & df.description.str.contains(pattern_description)
df_in_name_and_description_boolean

0          True
1          True
2          True
3          True
4          True
          ...  
178065    False
178066     True
178067    False
178068    False
178069    False
Length: 178070, dtype: bool

In [26]:
df_in_name_and_description = df[df_in_name_and_description_boolean]
df_in_name_and_description

id                                               name  \
0       238316428                                           COVID-19   
1       235374822                                           COVID-19   
2       239777191                                        coronavirus   
3       237129709                                        coronavirus   
4       234936988                                               ncov   
...           ...                                                ...   
178042  267669502                                            pydemic   
178046  267472666  simulation-model-of-interventions-to-interrupt...   
178054  268148998                                Epidemics-Modelling   
178064  269601203                                    CoronaDashboard   
178066  270034436                                      mzansi_corona   

                                                full_name  \
0                                 CSSEGISandData/COVID-19   
1                                  midas-network/COVID-19   
2                                 RamiKrispin/coronavirus   
3                               FoldingAtHome/coronavirus   
4                                         nextstrain/ncov   
...                                                   ...   
178042                      uiuc-covid19-modeling/pydemic   
178046  nicolaspenagos/simulation-model-of-interventio...   
178054                    pierpaolo28/Epidemics-Modelling   
178064                              StefH/CoronaDashboard   
178066                        marvinIsSacul/mzansi_corona   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178042  a python driver for epidemic modeling and infe...   
178046  I present software to simulate how biosecurity...   
178054  Modelling and tracking of epidemics data analy...   
178064  Een Corona Dashboard gebaseerd op cijfers van ...   
178066  Flutter app about South Africa's Corona Virus ...   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178042  https://api.github.com/repos/uiuc-covid19-mode...     False     False   
178046  https://api.github.com/repos/nicolaspenagos/si...     False     False   
178054  https://api.github.com/repos/pierpaolo28/Epide...     False     False   
178064  https://api.github.com/repos/StefH/CoronaDashb...     False     False   
178066  https://api.github.com/repos/marvinIsSacul/mza...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178042                 5               5            4  ...          True   
178046                 0               0            0  ...          True   
178054                 1   

In [27]:
df_in_name_and_description.shape[0]

66534

**66.534** repositorios.

------

### Comprobación del 62,7% de repositorios descartados si nos quedásemos con la última opción

In [28]:
df = pd.read_csv('df_repositorios.csv')
df_sin = df[~df_in_name_and_description_boolean]
df_sin

id                             name  \
20      241636482                      coronavirus   
40      237221585                       gatsby-map   
41      236218942                             cido   
48      237517471     Coronavirus-Chrome-Extension   
50      236273771                  corona-frontend   
...           ...                              ...   
178063  269479371                          jupyter   
178065  269527538  OpenWeatherMap-concat-histories   
178067  269906994              face-mask-detection   
178068  270013759                         frontend   
178069  270006438                          backend   

                                            full_name  \
20                         YaseenAbdullah/coronavirus   
40                                elinlutz/gatsby-map   
41                                 CIDO-ontology/cido   
48      WebDevSimplified/Coronavirus-Chrome-Extension   
50                          theleadio/corona-frontend   
...                                               ...   
178063                                  kclhi/jupyter   
178065         ALT-F1/OpenWeatherMap-concat-histories   
178067             jahnavi-prasad/face-mask-detection   
178068                               Tackode/frontend   
178069                                Tackode/backend   

                                              description  \
20                                                    NaN   
40      Mapping the coronavirus in react, gatsby.js an...   
41          CIDO: Coronavirus Infectious Disease Ontology   
48                                                    NaN   
50                                                    NaN   
...                                                   ...   
178063           :whale2: JupyterHub Docker configuration   
178065  Concatenate histories weather data collected b...   
178067  Simple project to detect if a person is wearin...   
178068                               Frontend for Tackode   
178069                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
20      https://api.github.com/repos/YaseenAbdullah/co...     False     False   
40      https://api.github.com/repos/elinlutz/gatsby-m...     False     False   
41      https://api.github.com/repos/CIDO-ontology/cid...     False     False   
48      https://api.github.com/repos/WebDevSimplified/...     False     False   
50      https://api.github.com/repos/theleadio/corona-...     False     False   
...                                                   ...       ...       ...   
178063  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
178065  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   
178068  https://api.github.com/repos/Tackode/frontend/...     False     False   
178069  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
20                    34              34           13  ...          True   
40                    31              31           12  ...          True   
41                    13              13            9  ...          True   
48                    24              24           10  ...          True   
50                    45              45           33  ...          True   
...                  ...             ...          ...  ...           ...   
178063                 2               2            0  ...          True   
178065                 1               1            0  ...          True   
178067                 6               6            7  ...          True   
178068                 0               0            0  ...          True   
178069                 0               0            0  ...          True   

        has_wiki                        homepage  \
20        

In [29]:
df_sin.sort_values(by=['stargazers_count'])

id                           name  \
93690   253104417                covid19-chatbot   
117101  361328496          Taller-Covid-Colombia   
117100  361553148     vue-tailwind-covid-tracker   
117099  361405214            flutter_covid_today   
117098  361355998       COVID-19-Cough-Detection   
...           ...                            ...   
96169   253216457            springer_free_books   
13534   260712390                     cwa-server   
2993    247821387                            app   
154209  260064828  exposure-notifications-server   
50852   245077032                            API   

                                        full_name  \
93690                     dbacall/covid19-chatbot   
117101               levf18/Taller-Covid-Colombia   
117100  Brian-Santeliz/vue-tailwind-covid-tracker   
117099            sing3demons/flutter_covid_today   
117098    HrithikNambiar/COVID-19-Cough-Detection   
...                                           ...   
96169                alexgand/springer_free_books   
13534                  corona-warn-app/cwa-server   
2993                  WorldHealthOrganization/app   
154209       google/exposure-notifications-server   
50852                              disease-sh/API   

                                              description  \
93690                                                 NaN   
117101                                                NaN   
117100                                                NaN   
117099                                                NaN   
117098  An attempt at INTERSPEECH 2021 Computational P...   
...                                                   ...   
96169   Python script to download all Springer books r...   
13534   Backend implementation for the Apple/Google ex...   
2993                                         COVID-19 App   
154209  Exposure Notification Reference Server | Covid...   
50852   API for Current cases and more stuff about COV...   

                                         contributors_url  archived  disabled  \
93690   https://api.github.com/repos/dbacall/covid19-c...     False     False   
117101  https://api.github.com/repos/levf18/Taller-Cov...     False     False   
117100  https://api.github.com/repos/Brian-Santeliz/vu...     False     False   
117099  https://api.github.com/repos/sing3demons/flutt...     False     False   
117098  https://api.github.com/repos/HrithikNambiar/CO...     False     False   
...                                                   ...       ...       ...   
96169   https://api.github.com/repos/alexgand/springer...     False     False   
13534   https://api.github.com/repos/corona-warn-app/c...     False     False   
2993    https://api.github.com/repos/WorldHealthOrgani...     False     False   
154209  https://api.github.com/repos/google/exposure-n...     False     False   
50852   https://api.github.com/repos/disease-sh/API/co...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
93690                  0               0            0  ...          True   
117101                 0               0            0  ...          True   
117100                 0               0            0  ...          True   
117099                 0               0            0  ...          True   
117098                 0               0            0  ...          True   
...                  ...             ...          ...  ...           ...   
96169               1633            1633          370  ...          True   
13534               1752            1752          336  ...         False   
2993                2060            2060          528  ...          True   
154209              2076            2076          289  ...         False   
50852               2289            2289          625  ...          True   

        has_wiki                                           homepage  \
93690       True                                               

In [30]:
df_sin_sorted = df_sin.sort_values(by=['stargazers_count'], ascending=False).head(20)
df_sin_sorted[['id', 'name', 'full_name', 'description', 'stargazers_count', 'html_url']]

id                                               name  \
50852   245077032                                                API   
154209  260064828                      exposure-notifications-server   
2993    247821387                                                app   
13534   260712390                                         cwa-server   
96169   253216457                                springer_free_books   
105038  254129456  Free_CyberSecurity_Professional_Development_Re...   
176821   21244714                                        tika-python   
7113    250585282      Amazon-Fresh-Whole-Foods-delivery-slot-finder   
64      237385601                   Getting-Things-Done-with-Pytorch   
177900  257567981                                Face-Mask-Detection   
176819  125756247                                   ESP32-Paxcounter   
176627  264477930                                 immuni-app-android   
102026  253851344                                Covid-19-Flutter-UI   
171365  268543048                                    covid-alert-app   
6793    250296192                                   coronavirus-data   
3784    248180072                                             makair   
143294  383424499             korea-covid-19-remaining-vaccine-macro   
27786   248910514                                                api   
176986  281475256                                            paperai   
118662  362534835                              covid-vaccine-booking   

                                                full_name  \
50852                                      disease-sh/API   
154209               google/exposure-notifications-server   
2993                          WorldHealthOrganization/app   
13534                          corona-warn-app/cwa-server   
96169                        alexgand/springer_free_books   
105038  gerryguy311/Free_CyberSecurity_Professional_De...   
176821                          chrismattmann/tika-python   
7113    ahertel/Amazon-Fresh-Whole-Foods-delivery-slot...   
64            curiousily/Getting-Things-Done-with-Pytorch   
177900                  chandrikadeb7/Face-Mask-Detection   
176819                        cyberman54/ESP32-Paxcounter   
176627                      immuni-app/immuni-app-android   
102026                    abuanwar072/Covid-19-Flutter-UI   
171365                            cds-snc/covid-alert-app   
6793                           nychealth/coronavirus-data   
3784                               makers-for-life/makair   
143294      SJang1/korea-covid-19-remaining-vaccine-macro   
27786                                    covid19india/api   
176986                                      neuml/paperai   
118662                      pallupz/covid-vaccine-booking   

                                              description  stargazers_count  \
50852   API for Current cases and more stuff about COV...              2289   
154209  Exposure Notification Reference Server | Covid...              2076   
2993                                         COVID-19 App              2060   
13534   Backend implementation for the Apple/Google ex...              1752   
96169   Python script to download all Springer books r...              1633   
105038  An awesome list of FREE resources for training...              1075   
176821  Tika-Python is a Python binding to the Apache ...              1062   
7113    A Mac tool that finds available delivery slots...              1049   
64      Jupyter Notebook tutorials on solving real-wor...               957   
177900  Face Mask Detection system based on computer v...               952   
176819  Wifi & BLE driven passenger flow metering with...               906   
176627   Official repository for the Android version o...               878   
102026                                                NaN               875   
171365  Exposure notification client application / App...               874   
6793                               

In [212]:
# show(df_sin_sorted[['id', 'name', 'full_name', 'description', 'stargazers_count', 'html_url']])

----

### 4.2.8.3 Estrategia de filtrado

Primero comprobamos las palabras claves en el nombre:

In [31]:
df_in_name

id                 name                        full_name  \
0       238316428             COVID-19          CSSEGISandData/COVID-19   
1       235374822             COVID-19           midas-network/COVID-19   
2       239777191          coronavirus          RamiKrispin/coronavirus   
3       237129709          coronavirus        FoldingAtHome/coronavirus   
4       234936988                 ncov                  nextstrain/ncov   
...           ...                  ...                              ...   
178054  268148998  Epidemics-Modelling  pierpaolo28/Epidemics-Modelling   
178056  268314248                   UI                    CovidToday/UI   
178061  268770101             coroname                mariabnd/coroname   
178064  269601203      CoronaDashboard            StefH/CoronaDashboard   
178066  270034436        mzansi_corona      marvinIsSacul/mzansi_corona   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178054  Modelling and tracking of epidemics data analy...   
178056                                                NaN   
178061                                                NaN   
178064  Een Corona Dashboard gebaseerd op cijfers van ...   
178066  Flutter app about South Africa's Corona Virus ...   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178054  https://api.github.com/repos/pierpaolo28/Epide...     False     False   
178056  https://api.github.com/repos/CovidToday/UI/con...     False     False   
178061  https://api.github.com/repos/mariabnd/coroname...     False     False   
178064  https://api.github.com/repos/StefH/CoronaDashb...     False     False   
178066  https://api.github.com/repos/marvinIsSacul/mza...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178054                 1               1            0  ...          True   
178056                 0               0            0  ...          True   
178061                 0               0            0  ...          True   
178064                 1               1            0  ...          True   
178066                 0               0            0  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1           True                                                NaN   
2           True         https://ramikrispin.github.io/coronavirus/   
3           True                          https://foldingathome.org   
4           True                        https://nextstrain.org/ncov   
...          ...                                                ...  

Filtramos los que tienen palabras claves en el nombre y nos quedamos con el resto para seguir analizándolo:

In [32]:
df_res_final = df_in_name #Aquí se irán acumulando los repositorios válidos

In [33]:
df_not_in_name = df[~df_in_name_boolean]

In [34]:
df_not_in_name

id                              name  \
40      237221585                        gatsby-map   
41      236218942                              cido   
64      237385601  Getting-Things-Done-with-Pytorch   
67      236146885                         pneumonia   
72      229427465                Hentai-discord-bot   
...           ...                               ...   
178063  269479371                           jupyter   
178065  269527538   OpenWeatherMap-concat-histories   
178067  269906994               face-mask-detection   
178068  270013759                          frontend   
178069  270006438                           backend   

                                          full_name  \
40                              elinlutz/gatsby-map   
41                               CIDO-ontology/cido   
64      curiousily/Getting-Things-Done-with-Pytorch   
67                                lispczz/pneumonia   
72                     Eddy-Arch/Hentai-discord-bot   
...                                             ...   
178063                                kclhi/jupyter   
178065       ALT-F1/OpenWeatherMap-concat-histories   
178067           jahnavi-prasad/face-mask-detection   
178068                             Tackode/frontend   
178069                              Tackode/backend   

                                              description  \
40      Mapping the coronavirus in react, gatsby.js an...   
41          CIDO: Coronavirus Infectious Disease Ontology   
64      Jupyter Notebook tutorials on solving real-wor...   
67                                       中国新型冠状病毒肺炎地级市疫情图   
72      A NSFW hentai discord bot with extra functiona...   
...                                                   ...   
178063           :whale2: JupyterHub Docker configuration   
178065  Concatenate histories weather data collected b...   
178067  Simple project to detect if a person is wearin...   
178068                               Frontend for Tackode   
178069                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
40      https://api.github.com/repos/elinlutz/gatsby-m...     False     False   
41      https://api.github.com/repos/CIDO-ontology/cid...     False     False   
64      https://api.github.com/repos/curiousily/Gettin...     False     False   
67      https://api.github.com/repos/lispczz/pneumonia...     False     False   
72      https://api.github.com/repos/Eddy-Arch/Hentai-...     False     False   
...                                                   ...       ...       ...   
178063  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
178065  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   
178068  https://api.github.com/repos/Tackode/frontend/...     False     False   
178069  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
40                    31              31           12  ...          True   
41                    13              13            9  ...          True   
64                   957             957          300  ...          True   
67                   356             356          100  ...          True   
72                    21              21           12  ...          True   
...                  ...             ...          ...  ...           ...   
178063                 2               2            0  ...          True   
178065                 1               1            0  ...          True   
178067                 6               6            7  ...          True   
178068                 0               0            0  ...          True   
178069                 0               0            0  ...          True   

        has_wiki                              homepage  \
40          True

Comprobamos los repositorios que tienen palabras relacionadas en la descripción:

In [35]:
df_in_description_boolean = df_not_in_name.description.str.contains(pattern_description)
df_in_description_boolean

40         True
41         True
64         True
67         True
72         True
          ...  
178063    False
178065    False
178067     True
178068    False
178069    False
Name: description, Length: 18913, dtype: object

Número de repositorios que tienen la descripción a nula:

In [36]:
df_in_description_boolean.isnull().sum()

140

In [37]:
#Rellenamos a False los valores nulos de la descripción
df_in_description_boolean = df_in_description_boolean.fillna(False)

df_in_description = df_not_in_name[df_in_description_boolean]
df_in_description

id                              name  \
40      237221585                        gatsby-map   
41      236218942                              cido   
64      237385601  Getting-Things-Done-with-Pytorch   
67      236146885                         pneumonia   
72      229427465                Hentai-discord-bot   
...           ...                               ...   
178037  267352452                    steam-lockdown   
178047  267575087                Smart-Food-Storage   
178050  246130172                         Airplanes   
178051  267858096      face_mask_detection_openvino   
178067  269906994               face-mask-detection   

                                          full_name  \
40                              elinlutz/gatsby-map   
41                               CIDO-ontology/cido   
64      curiousily/Getting-Things-Done-with-Pytorch   
67                                lispczz/pneumonia   
72                     Eddy-Arch/Hentai-discord-bot   
...                                             ...   
178037             digital-wellbeing/steam-lockdown   
178047                m-boutaleb/Smart-Food-Storage   
178050                          cgettings/Airplanes   
178051         mmphego/face_mask_detection_openvino   
178067           jahnavi-prasad/face-mask-detection   

                                              description  \
40      Mapping the coronavirus in react, gatsby.js an...   
41          CIDO: Coronavirus Infectious Disease Ontology   
64      Jupyter Notebook tutorials on solving real-wor...   
67                                       中国新型冠状病毒肺炎地级市疫情图   
72      A NSFW hentai discord bot with extra functiona...   
...                                                   ...   
178037  How has gaming changed during lockdown? Analys...   
178047  An intelligent application (very useful during...   
178050  Visualizing flights into LGA at the start of t...   
178051  Detect faces and determine whether people are ...   
178067  Simple project to detect if a person is wearin...   

                                         contributors_url  archived  disabled  \
40      https://api.github.com/repos/elinlutz/gatsby-m...     False     False   
41      https://api.github.com/repos/CIDO-ontology/cid...     False     False   
64      https://api.github.com/repos/curiousily/Gettin...     False     False   
67      https://api.github.com/repos/lispczz/pneumonia...     False     False   
72      https://api.github.com/repos/Eddy-Arch/Hentai-...     False     False   
...                                                   ...       ...       ...   
178037  https://api.github.com/repos/digital-wellbeing...     False     False   
178047  https://api.github.com/repos/m-boutaleb/Smart-...     False     False   
178050  https://api.github.com/repos/cgettings/Airplan...     False     False   
178051  https://api.github.com/repos/mmphego/face_mask...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
40                    31              31           12  ...          True   
41                    13              13            9  ...          True   
64                   957             957          300  ...          True   
67                   356             356          100  ...          True   
72                    21              21           12  ...          True   
...                  ...             ...          ...  ...           ...   
178037                 0               0            0  ...          True   
178047                 0               0            0  ...          True   
178050                 0               0            0  ...          True   
178051                35              35           11  ...          True   
178067                 6               6            7  ...          True   

        has_wiki                                           homepage  \
40 

Actualizamos en *df_res_final* con los repositorios que tienen palabras relacionadas en la descripción:

In [47]:
df_res_final = df_res_final.append(df_in_description)
df_res_final

id                          name  \
0       238316428                      COVID-19   
1       235374822                      COVID-19   
2       239777191                   coronavirus   
3       237129709                   coronavirus   
4       234936988                          ncov   
...           ...                           ...   
178037  267352452                steam-lockdown   
178047  267575087            Smart-Food-Storage   
178050  246130172                     Airplanes   
178051  267858096  face_mask_detection_openvino   
178067  269906994           face-mask-detection   

                                   full_name  \
0                    CSSEGISandData/COVID-19   
1                     midas-network/COVID-19   
2                    RamiKrispin/coronavirus   
3                  FoldingAtHome/coronavirus   
4                            nextstrain/ncov   
...                                      ...   
178037      digital-wellbeing/steam-lockdown   
178047         m-boutaleb/Smart-Food-Storage   
178050                   cgettings/Airplanes   
178051  mmphego/face_mask_detection_openvino   
178067    jahnavi-prasad/face-mask-detection   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178037  How has gaming changed during lockdown? Analys...   
178047  An intelligent application (very useful during...   
178050  Visualizing flights into LGA at the start of t...   
178051  Detect faces and determine whether people are ...   
178067  Simple project to detect if a person is wearin...   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178037  https://api.github.com/repos/digital-wellbeing...     False     False   
178047  https://api.github.com/repos/m-boutaleb/Smart-...     False     False   
178050  https://api.github.com/repos/cgettings/Airplan...     False     False   
178051  https://api.github.com/repos/mmphego/face_mask...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178037                 0               0            0  ...          True   
178047                 0               0            0  ...          True   
178050                 0               0            0  ...          True   
178051                35              35           11  ...          True   
178067                 6               6            7  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1           True                                                

A continuación filtramos, quedándonos con los que NO tienen palabras relacionadas en la descripción:

In [45]:
df_not_in_description = df_not_in_name[~df_in_description_boolean]
df_not_in_description

id                             name  \
79      229502804       data-visualisation-scripts   
140     141635301          Water-Monitoring-System   
157     237388368                        red-cross   
458     170732312                 limnoria-plugins   
842     155705971                  alm-api-backend   
...           ...                              ...   
178062  268856502               iot-contact-tracer   
178063  269479371                          jupyter   
178065  269527538  OpenWeatherMap-concat-histories   
178068  270013759                         frontend   
178069  270006438                          backend   

                                     full_name  \
79       Perishleaf/data-visualisation-scripts   
140       vinitshahdeo/Water-Monitoring-System   
157                       WeileiZeng/red-cross   
458                   oddluck/limnoria-plugins   
842                     Beor18/alm-api-backend   
...                                        ...   
178062                 fwcd/iot-contact-tracer   
178063                           kclhi/jupyter   
178065  ALT-F1/OpenWeatherMap-concat-histories   
178068                        Tackode/frontend   
178069                         Tackode/backend   

                                              description  \
79      Collection of scripts for data visualisation a...   
140     Water Monitoring System is an IOT based Liquid...   
157                                              官方公示数据概览   
458                   Limnoria plugins I wrote or forked.   
842     Comenzo como desafio almundo.com y ahora estoy...   
...                                                   ...   
178062  Decentralized contact tracing system supportin...   
178063           :whale2: JupyterHub Docker configuration   
178065  Concatenate histories weather data collected b...   
178068                               Frontend for Tackode   
178069                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
79      https://api.github.com/repos/Perishleaf/data-v...     False     False   
140     https://api.github.com/repos/vinitshahdeo/Wate...     False     False   
157     https://api.github.com/repos/WeileiZeng/red-cr...     False     False   
458     https://api.github.com/repos/oddluck/limnoria-...     False     False   
842     https://api.github.com/repos/Beor18/alm-api-ba...     False     False   
...                                                   ...       ...       ...   
178062  https://api.github.com/repos/fwcd/iot-contact-...     False     False   
178063  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
178065  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178068  https://api.github.com/repos/Tackode/frontend/...     False     False   
178069  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
79                    80              80           90  ...          True   
140                  128             128          245  ...          True   
157                   19              19            4  ...          True   
458                   33              33            8  ...          True   
842                   11              11            2  ...          True   
...                  ...             ...          ...  ...           ...   
178062                 1               1            0  ...          True   
178063                 2               2            0  ...          True   
178065                 1               1            0  ...          True   
178068                 0               0            0  ...          True   
178069                 0               0            0  ...          True   

        has_wiki                                           homepage  \
79          True                                                NaN   
140 

In [46]:
df_not_in_description.shape[0]

1347

Nos quedan 1347 repositorios que habrá que analizar individualmente para saber si están relacionados con la COVID-19 o no. Para ello consultaremos los *topics* que los componen, a fin de encontrar tópicos relacionados con la pandemia.

In [221]:
# show(df_not_in_description)

### Comprobación de *topics* en repositorios

In [48]:
token = "" # Rellenar con token generado en GitHub
header = {'Authorization': 'token %s' % token, 'Accept':'application/vnd.github.mercy-preview+json'}

In [49]:
df_topics = pd.DataFrame(columns=['id', 'topics'])

for ind in df_not_in_description.index:
    print("\n\n -- OBTENIENDO TOPICS DEL REPOSITORIO {} --".format(df_not_in_description['name'][ind]))
    
    query = "?q=per_page=100"

    response = requests.get('https://api.github.com/repos/' + df_not_in_description['full_name'][ind] + "/topics" + query, 
                            headers=header)
    response_json = response.json()
    
    if "names" in response_json:
        print(response_json["names"])

        df_topics.loc[ind] = [df_not_in_description['id'][ind], response_json["names"]]
    else:
        df_topics.loc[ind] = [df_not_in_description['id'][ind], None]
        
    print("Esperando 0,5 segundos...")
    time.sleep(0.5)



 -- OBTENIENDO TOPICS DEL REPOSITORIO data-visualisation-scripts --
['datavisualization', 'python3', 'covid-19', 'dashborad', 'matplotlib', 'plotly-dash', 'coronavirus']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Water-Monitoring-System --
['iot', 'water-monitoring', 'jquery', 'javascript', 'arduino', 'ultrasonic-sensors', 'hardware', 'nodejs', 'django', 'api', 'rgsoc', 'gssoc20', 'gssoc', 'covid-19', 'coronavirus-tracking', 'coronavirus', 'coronavirus-real-time', 'hacktoberfest', 'hacktoberfest2020']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO red-cross --
['red-cross', 'github-pages', 'coronavirus', 'covid-19', 'open-source-wuhan', 'ncov']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO limnoria-plugins --
['limnoria', 'irc', 'ascii-art', 'jeopardy', 'uno', 'interactive-fiction', 'lyrics', 'irc-art', 'ansi-art', 'cards-against-humanity', 'zork', 'limnoria-plugins', 'trivia', 'supybot', 'supybot-plugin', 'dice-roller', '



 -- OBTENIENDO TOPICS DEL REPOSITORIO Many-Api --
['api', 'garfield', 'covid19', 'coronavirus', 'c19', 'pokemon', 'pokemondata', 'pokemonapi', 'garfieldapi', 'atla', 'coronavirus-data', 'mcu', 'marvel', 'marvelquotes', 'twitter', 'tweets', 'marvel-api', 'covidapi', 'jokes', 'jokes-api']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO status --
['vkontakte', 'vk-api', 'coronavirus']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO awesome-confinement --
['awesome-list', 'awesome-lists', 'coronavirus', 'confinement']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO OpenVentilator --
['ventilator', 'arduino', 'covid-19', 'covid', 'coronavirus']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO KoronaKartta --
['coronavirus', 'map', 'finland', 'history']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO attestation-deplacement-derogatoire --
['france', 'confinement', 'covid-19', 'coronavirus']
Esperando 0



 -- OBTENIENDO TOPICS DEL REPOSITORIO super-simple-ventilator --
['ventilator', 'ventilator-firmware', 'platformio', 'coronavirus', 'covid-19', 'arduino']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO orange-cxr-classifier --
['covid-19', 'coronavirus', 'xray', 'chest', 'machine-learning', 'orange']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO RIST --
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO 7dayserlangen --
['hacktoberfest', 'coronavirus', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO pyross --
['covid-19', 'infectious-disease-models', 'epidemiological-predictions', 'epidemic-simulations', 'coronavirus', 'sars-cov-2', 'compartment-models', 'epidemiological-models', 'pyross']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO camara-descontaminacao-ar --
['healtcare', 'coronavirus', 'covid-19', 'open-source']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORI

['delivery', 'bem', 'covid-19', 'coronavirus', 'small', 'producers', 'brazilian']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Crawling --
['crawling', 'crawling-python', 'selenium', 'beautifulsoup', 'lda', 'lda-model', 'algorithms', 'wordcloud', 'coronavirus', 'covid19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Prioritize-Vaccine-Delivery --
['python', 'ai-ml', 'covid-19', 'coronavirus', 'vaccine', 'ai-model', 'ml-model', 'covidindia', 'vaccine-distribution', 'ey-hackathon']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO CO2_traffic_light --
['co2', 'sensor', 'arduino', 'python', 'stl', '7segment', 'rgb-led', 'arduinonano', 'coronavirus', 'air-quality']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO datamuseum.github.io --
['coronavirus', 'dashboard', 'covid-19', 'coronavirus-real-time']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO kryzysowa-kawa --
['crisis-related', 'coronavirus'



 -- OBTENIENDO TOPICS DEL REPOSITORIO Hackathon2021 --
['hackathon', 'iot', 'octopus', 'esp8266', 'co2', 'coronavirus', 'regression', 'physcomp']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO ExpCowin --
['nodejs', 'coronavirus']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO swaas-bot --
['nodejs', 'expressjs', 'javascript', 'mongodb', 'coronavirus', 'vaccination', 'india', 'whastappbot']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO bored-af --
['quarantine', 'quarantine-project', 'covid-19', 'python', 'coronavirus']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Amazon-Whole-Foods-Delivery-Slots-Finder --
['whole-foods', 'coronavirus', 'delivery-slots', 'covid-19', 'stay-home', 'amazon', 'chrome-extension', 'grocery-delivery', 'food-delivery', 'mac', 'windows', 'google-chrome', 'delivery-slot-alert', 'quarantine', 'alert']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO cowin-tracker --



 -- OBTENIENDO TOPICS DEL REPOSITORIO 6-ft-apart --
['greenfoot', 'java', 'coronavirus']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO M5Stack_Healthy_code_tracer --
['m5stack', 'micropython', 'arduino', 'onenet', 'uiflow', 'maixpy', 'coronavirus']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO OKorona --
['coronavirus', 'javascript', 'nodejs', 'mapbox-gl', 'api', 'covid19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO ProximityApp --
['coronavirus', 'mobile']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO not-busy-backend --
['covid', 'covid-19', 'coronavirus', 'express', 'node', 'typescript']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO not-busy-frontend --
['covid-19', 'covid19', 'coronavirus', 'businesses', 'popularity', 'wait-times']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO software-donation --
['covid-19', 'coronavirus', 'remote', 'remote-work', 'donating

['covid-19', 'covid19', 'covid', 'covid19-data', 'covid-data']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO immuni-tek-sender --
['covid', 'telegram', 'immuni', 'tek']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO TwiCo --
['python3', 'flask', 'microservices', 'soa', 'pm2', 'vue', 'vuetify', 'amcharts', 'sentiment-analysis', 'twitter', 'covid', 'mapbox', 'locationiq', 'typescript', 'nodejs', 'google-oauth2', 'artificial-intelligence', 'github-oauth-authentation']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Projeto-Banco-de-Dados --
['projeto', 'mysql', 'covid']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO r-package-assessment-msobanq --
['covid', 'shiny', 'shiny-apps', 'packages']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO helpthemidlands --
['hacktoberfest', 'covid', 'hackthemidlands']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO TeamReispar-C3DataHackathonSo

['education', 'edtech', 'schools', 'covid']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO vaccipy --
['corona', 'impfterminservice', 'vaccination', 'covid', 'covid-19', 'bot', 'python', 'selenium', 'impftermin', 'vaccine']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO miq-nz-booking-tools --
['miq', 'new-zealand', 'covid', 'nz-managed-isolation', 'quarantine', 'booking']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO check-the-fridge --
['covid', 'vaccines', 'ontario', 'api']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO essentialsapp --
['covid', 'essentials', 'flutter']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO impf-bot --
['bot', 'covid', 'vaccination', 'covid19', 'impftermin', 'kotlin', 'selenium', 'java']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO GetUsPPE --
['ppe', 'getusppe', 'covid-19', 'covid19', 'covid']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPI



 -- OBTENIENDO TOPICS DEL REPOSITORIO BERTweet --
['python3', 'bert', 'roberta', 'transformers', 'fairseq', 'language-model', 'english', 'part-of-speech-tagging', 'ner', 'named-entity-recognition', 'text-classification', 'sentiment-analysis', 'irony-detection', 'english-tweets', 'covid-19', 'covid19', 'covid', 'bertweet', 'bertweet-covid19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO where-can-we-meet --
['covid', 'covid-19', 'covid19', 'map', 'maps']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO uniforme-bonja --
['covid-19', 'covid', 'react', 'reactjs', 'uniforme', 'bonja', 'uniformebonja', 'terceirao', 'escola']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO BUZZ --
['covid', 'covid-19', 'voucher', 'vouchers', 'react', 'store', 'market', 'opensource']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO vueground --
['xstate', 'kanban', 'covid', 'vue']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL R

['covid19', 'placetracing']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO CareQuest --
['covid19', 'hospital-management-system', 'plasma-bank']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO folding-at-home --
['foldingathome', 'fah', 'docker', 'docker-compose', 'cancer', 'covid-19', 'covid-data', 'covid19', 'distributed-computing', 'distributed-systems', 'howtocodewell']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO BravoOscarTango --
['discord-py', 'discord-bot', 'flight-simulation', 'utility', 'covid19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO people-registry --
['covid-19', 'covid19', 'visitor-tracking', 'visitor-management', 'contactless-devices', 'contactless', 'vue']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Machine-Learning-Exercises --
['machine-learning-algorithms', 'machine-learning', 'jupyter-notebook', 'labs', 'ipynb-jupyter-notebook', 'ml', 'scikitlearn-machine-lea

['ohif', 'medical-imaging', 'machine-learning', 'covid19', 'covid-19', 'chest-xray']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO ninjam --
['ninjam', 'ninjamserver', 'covid19', 'jam', 'music']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO project-maskwearing --
['covid19', 'r', 'rmarkdown']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO gagopa --
['react', 'amplify', 'graphql', 'appsync', 'aws', 'travel', 'covid19', 'japan']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO project-catdensity --
['covid19', 'r', 'rmarkdown']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO project-excessmortality --
['covid19', 'r', 'rmarkdown']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO project-nonpharmainterventions --
['covid19', 'r', 'rmarkdown']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO project-youthunemployment --
['covid19', 'r', 'rmarkdown']
Esperando 0,5 



 -- OBTENIENDO TOPICS DEL REPOSITORIO KeggDrugVirtualScreening --
['covid19', 'virtual-screening', 'candidates', 'descriptors', 'molecular-modeling', 'electrostatics', 'kegg', 'atc', 'drug-discovery', 'cheminformatics']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO delivery-slot-notify --
['delivery-window', 'amazon', 'amazon-fresh', 'wholefoods', 'covid-19', 'covid19', 'instacart', 'primenow', 'grocery-delivery', 'groceries', 'groceries-online', 'asda', 'usa', 'uk', 'france', 'india', 'canada']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO india-vaccine-frontend --
['covid19', 'vaccine-availability']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO cowin18plus --
['india', 'covid19', 'vaccination', 'vaccine-availability']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO api-service --
['covid-19', 'covid19', 'pandemic', 'crowdsourcing', 'covid-19-india', 'kotlin', 'ktor', 'postgresql', 'sql', 'sqldelight', 'gr



 -- OBTENIENDO TOPICS DEL REPOSITORIO ventilator --
['ventilator', 'ventilator-designs', 'emergency-ventilator', 'covid-19', 'covid19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Bioinformatics --
['bioinformatics', 'python', 'covid19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Data_analysis_with_Python --
['data-analysis', 'python', 'python3', 'covid19', 'covid19-data']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO KeepWorkingFromHome --
['workfromhome', 'wfh', 'powershell', 'basic', 'chrome', 'covid-19', 'covid19', 'dashboard']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO flask_chartjs_drilldown_example_project --
['flask', 'chartjs', 'drilldown', 'covid19', 'csv', 'data-visualization', 'chart', 'time-series', 'line-chart', 'public-dataset']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO hub-for-good-list --
['digitalocean', 'hub-for-good', 'covid19', 'covid-19', 'digitalocean

['emergency-response', 'covid-19', 'healthcare', 'baltimore-city', 'code-for-baltimore', 'code-for-america', 'civic-tech', 'vuejs', 'rapid-response']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO catch --
['science', 'genomics', 'genome', 'viral', 'sequencing', 'ngs', 'dna', 'bioinformatics', 'metagenomics', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Bmore-Responsive --
['emergency-response', 'covid-19', 'api', 'contact-management', 'civic-tech', 'code-for-america', 'code-for-baltimore', 'nodejs', 'rapid-response']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO frontend --
['vue', 'vuejs', 'wuhan-support', 'science', 'openness', 'support', 'covid-19', 'covid-19-data']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO monoloco --
['3d-object-detection', '3d-detection', '3d-deep-learning', 'pytorch', 'computer-vision', 'deep-learning', 'machine-learning', 'pose-estimation', 'human-pose-estimation', 

['covid-19', 'computer-vision', 'artificial-intelligence', 'dataset', 'machine-learning', 'deep-learning', 'blockchain']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO BiLevel-Graph-Neural-Network --
['graph-convolutional-networks', 'graph-attention-networks', 'drug-drug-interaction', 'icml', 'covid-19', 'drugbank', 'graph-neural-networks', 'deep-learning', 'representation-learning']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO iwashere --
['hacktoberfest', 'covid-19', 'backend', 'spring-boot', 'kotlin', 'self-hosted', 'docker', 'contact-tracing']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO estudos_plotly_chartstudio --
['dados', 'pandas-python', 'matplotlib', 'plotly', 'plotly-dash', 'covid-19', 'bitcoin', 'podcasts']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Air-Traffic --
['jet-fuel', 'demand', 'air-traffic', 'covid-19', 'oil']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO mask-



 -- OBTENIENDO TOPICS DEL REPOSITORIO envirology.github.io --
['sars-cov-2', 'sewage', 'imperial-college-london', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO unics_social --
['react', 'social-network', 'covid-19', 'hacktoberfest']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO My-Projects --
['project', 'python', 'html', 'covid-19', 'covid19-data', 'coursera']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO koodikoira.github.io --
['nlp', 'nlp-machine-learning', 'covid-19', 'blog', 'cv', 'research', 'python3', 'jupyter-notebook']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Python_GUI --
['python', 'gui', 'covid-19', 'tracker']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO agri-ticket-map --
['agriculture', 'taiwan', 'coupons', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Adv_DS_Capstone_Project --
['python3', 'maskdetection', 'covid-19', 'r



 -- OBTENIENDO TOPICS DEL REPOSITORIO li-wenliang --
['covid-19', 'freecodecamp']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO social-data --
['risk', 'data-gathering', 'evictions', 'housing', 'county-level', 'compare-counties', 'burdened-households', 'python-scripts', 'fred', 'preventing-evictions', 'eviction', 'database', 'data-analysis', 'rent', 'cost', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO cdmx_challenge --
['python', 'covid-19', 'mexico', 'sars-cov-2', 'cdmx-challenge']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO teamlovelace --
['machine-learning', 'python3', 'covid-19', 'data-science', 'sagemaker', 'jupyter-notebook', 'aws-s3', 'mobility-data']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO goCrawler --
['golang', 'crawler', 'nlp', 'ngrams', 'text-mining', 'textual-analysis', 'corpus-linguistics', 'covid-19', 'health-data', 'clinical-research', 'redis', 'redis-cache', 'yaml', 



 -- OBTENIENDO TOPICS DEL REPOSITORIO Blockchain-Managed-Social-Distancing-Detector --
['computer-vision', 'blockchain', 'database', 'covid-19', 'social-distancing-detection', 'social-distance-monitoring']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO real-time-twitter-sentiment-analysis --
['python', 'tweepy-api', 'elasticsearch', 'logstash', 'kibana', 'kafka', 'docker', 'streaming', 'sentiment-analysis', 'deep-learning', 'covid-19', 'mongodb', 'docker-container', 'tweets', 'pipeline', 'visualisation']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Documentation --
['covid-19', 'epidemiological-predictions']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO All_Python --
['python3', 'python', 'zodiac', 'tkinter-gui', 'covid-19', 'network-programming', 'network-automation']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO 1_011_a_infektionsfall_uebermittellung --
['covid-19', 'covid-api', 'healthcare', 'pilot', '



 -- OBTENIENDO TOPICS DEL REPOSITORIO inzidenzcom --
['covid-19', 'hacktoberfest', 'hacktoberfest2020', 'germany']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Room-Counter --
['python', 'covid-19', 'machine-learning', 'opencv', 'pytorch']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO flow --
['lims', 'covid-19', 'swabseq', 'labgrid', 'laboratory']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO DarknetMod --
['yolov3', 'darknet53', 'computer-vision', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO BeeSafe --
['tracing-applications', 'covid-19', 'crowd-analysis', 'contact-tracing']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO coburg19 --
['corona', 'covid-19', 'coburg', 'svelte', 'api', 'rki', 'sapper']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO co2ampel --
['co2-sensor', 'co2-ampel', 'co2', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS 

['lighthouse', 'charts', 'johns-hopkins-university', 'dashboard', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO MedVista --
['nodejs', 'mongodb', 'covid-19', 'api-rest']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO kakao-qr --
['nodejs', 'typescript', 'kakaotalk', 'covid-19', 'qrcode', 'cheerio', 'got', 'korean']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Teamwork-API --
['teamwork', 'jwt-bearer-tokens', 'auth0', 'swagger-ui', 'spring-boot', 'covid-19', 'remote-work']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO MoroccoGeoMap2020 --
['maps', 'morocco', 'maghreb', 'world-map', 'geamap', 'covid-19', 'data', 'python']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO higan --
['covid-19', 'blockchain', 'golang']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO 100meter-app --
['covid-19', 'safety', 'location-based']
Esperando 0,5 segundos...


 -- OBTENIENDO TO

['covid-19', 'school', 'education']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Exploratory_Data_Analysis --
['machine-learning', 'machine-learning-algorithms', 'covid-19', 'flowers-classification', 'jupyter-notebook']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Semi-autonomous-UV-sterilization-bot --
['sterilization', 'uva-solutions', 'semi-autonomous', 'esp32', 'arduino', 'bot', 'coppeliasim', 'bldc-motor-controller', 'spiffs-memory', 'path-planning', 'obstacle-avoidance', 'ultrasonic-sensor', 'docking', 'freertos', 'iot-application', 'uv', 'uv-radiation', 'uv-exposure', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO AmboVent --
['covid-19', 'ventilator', 'rmvs', 'ambu']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO srijan-gsoc-2020 --
['federated-learning', 'bioinformatics', 'gsoc-2020', 'pygrid', 'pysyft', 'openmined', 'differential-privacy', 'multiparty-computation', 'gtex', 'covid-19', 



 -- OBTENIENDO TOPICS DEL REPOSITORIO mask-up-js --
['javascript', 'php', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO zurich_walks --
['pedestrian-tracking', 'covid-19', 'zurich', 'gis', 'r', 'analysis']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO pandemia-parliament --
['government', 'politics', 'online-conferences', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO keepyourdistanceclub.github.io --
['covid-19', 'stay-home', 'social-distancing']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Face-Shield --
['covid-19', 'face-sheild', 'face-mask']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO QuarantineFacility --
['covid-19', 'quarantine', 'quarantine-p', 'admin-dashboard', 'django-rest-framework', 'reactjs']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO book --
['covid-19', 'research', 'booking-system', 'university', 'hackaton', 'lauzhackaga



 -- OBTENIENDO TOPICS DEL REPOSITORIO python_assignment --
['python', 'covid-19', 'data', 'pandas', 'numpy', 'matphotlib', 'pyplot', 'datascience', 'tnl']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO C2N3-C3N3 --
['css', 'html', 'javascript', 'css3', 'flexbox', 'sass', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO EvdeKal --
['covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO EpiJS --
['epidemiology', 'modelling', 'covid-19', 'disease-modeling']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO WeiBoMonitor --
['covid-19', 'coolpush']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO picce_recircula --
['covid-19', 'sustainability', 'python', 'streaming']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Offen-in-5-Flowchart --
['oeffnungsperspektive', 'deutschland', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO leitos --
['co

['covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO hospitals-hifld --
['aws-data-exchange', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Equipool --
['android', 'java', 'covid-19', 'xml']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO e-yantra_competition --
['healthcare', 'iot', 'hardware', 'e-yantra', 'covid-19', 'raspberry-pi']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO saapshot --
['camera', 'toolkit', 'tools', 'demo', 'developer', 'testing', 'termux', 'terminal', 'game-engine', 'developer-tools', 'deface', 'wp', 'plugins', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO xrays-and-gradcam --
['fine-tuning', 'vgg16', 'resnet18', 'densenet121', 'gradcam', 'pytorch-implementation', 'covid-19', 'xrays', 'transfer-learning', 'imbalanced-data', 'oversampling', 'radiographs', 'pneumonia', 'deep-learning', 'cnn', 'early-stopping', 'localization']
Esperando 0,



 -- OBTENIENDO TOPICS DEL REPOSITORIO GetMeSlot --
['react-native', 'covid-19', 'vaccination', 'vaccine', 'dose-slot-booking', 'vaccine-availability']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Performed-text-mining-on-tweets-using-keywords-to-find-the-availability-of-hospital-beds-in-the-stat --
['ec2-instance', 'amazon-kinesis-console', 'beds', 'kinesis', 'oxygen', 'covid-19', 'life', 'save']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO vnb --
['telegram', 'cowin', 'rust', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO CowinVaccineNotifier --
['cowin', 'vaccination', 'vaccination-centers', 'covid-19', 'cowin-api', 'cowin-notifier']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Basic-Machine-Learning-Projects --
['machine-learning', 'machine-learning-algorithms', 'machine-learning-projects', 'data-science', 'database', 'deep-learning', 'csv-files', 'linear-regression', 'artificial-intellig



 -- OBTENIENDO TOPICS DEL REPOSITORIO aiwondergirls-icu-ops --
['healthcare', 'covid-19', 'machine-learning', 'mlrun', 'iguazio', 'diabetes-prediction', 'mlops-for-good-hackathon']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO 2021-esos-nces --
['r', 'rstats', 'covid-19', 'nces']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO data-analysis-projects --
['data-analysis', 'covid-19', 'netflix', 'pandas', 'python', 'tableau']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO EO2HO --
['companies-house', 'eat-out-to-help-out', 'covid-19', 'firm-creation']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO InfoG --
['api', 'ip', 'ddd', 'bank-account', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO oxygen --
['covid-19', 'oxymeter', 'hospital']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Discord-Obecnosciobot --
['discord', 'covid-19', 'online-classroom']
Esperando 0,5 

['covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO vund-karte --
['vaccine', 'vaccine-friendly', 'map', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO VaxPass --
['javascript', 'covid-19', 'reactnative', 'expo', 'firebase', 'crypto']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Cowin-Scrape --
['cowin', 'cowin-vaccine-tracker', 'vaccine', 'vaccine-availability', 'python', 'webscraping', 'covid-19', 'covid19-data', 'vaccine-tracker', 'covid-19-vaccination']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO realtime_r0_brazil --
['covid-19', 'coronavirus-analysis', 'hacktoberfest']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Python-Projects --
['python', 'python-project', 'sorting-algorithms', 'sorting-algorithm-visualizations', 'steganography', 'steganography-algorithms', 'sudokusolver', 'pong-game', 'covid-19', 'coronavirus-tracking', 'coronavirus-real-time', 'coronavir

['music', 'choir', 'virtualchoir', 'multi-track', 'multi-track-audio', 'recording', 'recording-app', 'corona', 'covid-19', 'webapp']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO greenpoint-face-shields --
['brooklyn', '3d-printing', 'diy', 'face-shields', 'covid-19', 'greenpoint', 'new-york', 'nyc']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO VirtQueue --
['social-distancing', 'queueing', 'virtual-queue', 'virtualqueue', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Cerberus-Multivent --
['ventilation', 'medicine', 'medical-device', 'covid-19', 'toronto']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO CCCSL-Codes --
['non-pharmaceutical-interventions', 'complexity-science-hub', 'npi', 'covid-19', 'codes', 'visualization', 'clustering', 'heatmap', 'cccsl']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO exposure-notifications-android --
['android', 'covid-19']
Esperando 0,5 se

['yolo', 'yolov3', 'mfc', 'darknet53', 'covid-19']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO geo-heatmap-android --
['worldmap', 'heatmap', 'android-application', 'covid-19', 'kotlin-android', 'data-visualization', 'map-heatmap-android', 'geo-heatmap']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO REMOTE-EDUCATION-APP---EMAGISTER --
['android', 'android-application', 'online-classroom', 'video-conferencing', 'covid-19', 'classroom', 'online-invigilator', 'secure-examination-environment', 'chat', 'chat-room-android', 'assignment-submission-system', 'appointment-management-system', 'appointment-scheduling', 'education', 'teachers', 'video', 'invigilate-students', 'blocking-students']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS DEL REPOSITORIO Data-Analysis-Projects --
['data-visualization', 'data-analysis', 'covid-19', 'text-analysis', 'seaborn', 'matplo', 'plotly', 'cufflinks', 'python']
Esperando 0,5 segundos...


 -- OBTENIENDO TOPICS 

In [50]:
df_topics

id                                             topics
79      229502804  [datavisualization, python3, covid-19, dashbor...
140     141635301  [iot, water-monitoring, jquery, javascript, ar...
157     237388368  [red-cross, github-pages, coronavirus, covid-1...
458     170732312  [limnoria, irc, ascii-art, jeopardy, uno, inte...
842     155705971  [mongodb, nodejs, api, apirest, javascript, gr...
...           ...                                                ...
178062  268856502       [contact-tracing, covid-19, iot, smartphone]
178063  269479371                 [jupyterlab, jupyterhub, covid-19]
178065  269527538  [eosc, eosc-secretariat, openweathermap-api, o...
178068  270013759                       [covid-19, qrcode, frontend]
178069  270006438   [covid-19, qrcode, rust, backend, covid-journal]

[1347 rows x 2 columns]

Exportamos el resultado a CSV:

In [51]:
df_topics.to_csv(r'repositorios_restantes_con_topics.csv', index = False, encoding="utf-8-sig")

Lo leemos:

In [73]:
df_topics = pd.read_csv('repositorios_restantes_con_topics.csv')
df_topics

id                                             topics
0     229502804.0  ['datavisualization', 'python3', 'covid-19', '...
1     141635301.0  ['iot', 'water-monitoring', 'jquery', 'javascr...
2     237388368.0  ['red-cross', 'github-pages', 'coronavirus', '...
3     170732312.0  ['limnoria', 'irc', 'ascii-art', 'jeopardy', '...
4     155705971.0  ['mongodb', 'nodejs', 'api', 'apirest', 'javas...
...           ...                                                ...
1342  268856502.0  ['contact-tracing', 'covid-19', 'iot', 'smartp...
1343  269479371.0           ['jupyterlab', 'jupyterhub', 'covid-19']
1344  269527538.0  ['eosc', 'eosc-secretariat', 'openweathermap-a...
1345  270013759.0                 ['covid-19', 'qrcode', 'frontend']
1346  270006438.0  ['covid-19', 'qrcode', 'rust', 'backend', 'cov...

[1347 rows x 2 columns]

El campo *id* se ha guardado como *float*. Lo convertimos a *int*:

In [74]:
df_topics.id = df_topics.id.astype(int)
df_topics

id                                             topics
0     229502804  ['datavisualization', 'python3', 'covid-19', '...
1     141635301  ['iot', 'water-monitoring', 'jquery', 'javascr...
2     237388368  ['red-cross', 'github-pages', 'coronavirus', '...
3     170732312  ['limnoria', 'irc', 'ascii-art', 'jeopardy', '...
4     155705971  ['mongodb', 'nodejs', 'api', 'apirest', 'javas...
...         ...                                                ...
1342  268856502  ['contact-tracing', 'covid-19', 'iot', 'smartp...
1343  269479371           ['jupyterlab', 'jupyterhub', 'covid-19']
1344  269527538  ['eosc', 'eosc-secretariat', 'openweathermap-a...
1345  270013759                 ['covid-19', 'qrcode', 'frontend']
1346  270006438  ['covid-19', 'qrcode', 'rust', 'backend', 'cov...

[1347 rows x 2 columns]

Repositorios que no tienen *topics*:

In [75]:
df_topics.topics.isnull().sum()

4

Unimos este dataframe con el que tiene todo el contenido de los repositorios:

In [76]:
df_not_in_description_new = df_not_in_description.join(df_topics.set_index('id'), on='id')
df_not_in_description_new

id                             name  \
79      229502804       data-visualisation-scripts   
140     141635301          Water-Monitoring-System   
157     237388368                        red-cross   
458     170732312                 limnoria-plugins   
842     155705971                  alm-api-backend   
...           ...                              ...   
178062  268856502               iot-contact-tracer   
178063  269479371                          jupyter   
178065  269527538  OpenWeatherMap-concat-histories   
178068  270013759                         frontend   
178069  270006438                          backend   

                                     full_name  \
79       Perishleaf/data-visualisation-scripts   
140       vinitshahdeo/Water-Monitoring-System   
157                       WeileiZeng/red-cross   
458                   oddluck/limnoria-plugins   
842                     Beor18/alm-api-backend   
...                                        ...   
178062                 fwcd/iot-contact-tracer   
178063                           kclhi/jupyter   
178065  ALT-F1/OpenWeatherMap-concat-histories   
178068                        Tackode/frontend   
178069                         Tackode/backend   

                                              description  \
79      Collection of scripts for data visualisation a...   
140     Water Monitoring System is an IOT based Liquid...   
157                                              官方公示数据概览   
458                   Limnoria plugins I wrote or forked.   
842     Comenzo como desafio almundo.com y ahora estoy...   
...                                                   ...   
178062  Decentralized contact tracing system supportin...   
178063           :whale2: JupyterHub Docker configuration   
178065  Concatenate histories weather data collected b...   
178068                               Frontend for Tackode   
178069                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
79      https://api.github.com/repos/Perishleaf/data-v...     False     False   
140     https://api.github.com/repos/vinitshahdeo/Wate...     False     False   
157     https://api.github.com/repos/WeileiZeng/red-cr...     False     False   
458     https://api.github.com/repos/oddluck/limnoria-...     False     False   
842     https://api.github.com/repos/Beor18/alm-api-ba...     False     False   
...                                                   ...       ...       ...   
178062  https://api.github.com/repos/fwcd/iot-contact-...     False     False   
178063  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
178065  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178068  https://api.github.com/repos/Tackode/frontend/...     False     False   
178069  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_wiki  \
79                    80              80           90  ...      True   
140                  128             128          245  ...      True   
157                   19              19            4  ...      True   
458                   33              33            8  ...      True   
842                   11              11            2  ...      True   
...                  ...             ...          ...  ...       ...   
178062                 1               1            0  ...      True   
178063                 2               2            0  ...      True   
178065                 1               1            0  ...      True   
178068                 0               0            0  ...      True   
178069                 0               0            0  ...      True   

                                                 homepage  \
79                                                    NaN   
140     https://vinitshahdeo.github.io/Water-Monitorin...   
157        

In [77]:
df_not_in_description_new.topics.isnull().sum()

4

In [57]:
show(df_not_in_description_new)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI


Lo exportamos a CSV:

In [78]:
df_not_in_description_new.to_csv(r'repositorios_restantes_con_topics_filtrado.csv', index = False, encoding="utf-8-sig")

In [80]:
df_not_in_description_new = pd.read_csv('repositorios_restantes_con_topics_filtrado.csv')
df_not_in_description_new

id                             name  \
0     229502804       data-visualisation-scripts   
1     141635301          Water-Monitoring-System   
2     237388368                        red-cross   
3     170732312                 limnoria-plugins   
4     155705971                  alm-api-backend   
...         ...                              ...   
1342  268856502               iot-contact-tracer   
1343  269479371                          jupyter   
1344  269527538  OpenWeatherMap-concat-histories   
1345  270013759                         frontend   
1346  270006438                          backend   

                                   full_name  \
0      Perishleaf/data-visualisation-scripts   
1       vinitshahdeo/Water-Monitoring-System   
2                       WeileiZeng/red-cross   
3                   oddluck/limnoria-plugins   
4                     Beor18/alm-api-backend   
...                                      ...   
1342                 fwcd/iot-contact-tracer   
1343                           kclhi/jupyter   
1344  ALT-F1/OpenWeatherMap-concat-histories   
1345                        Tackode/frontend   
1346                         Tackode/backend   

                                            description  \
0     Collection of scripts for data visualisation a...   
1     Water Monitoring System is an IOT based Liquid...   
2                                              官方公示数据概览   
3                   Limnoria plugins I wrote or forked.   
4     Comenzo como desafio almundo.com y ahora estoy...   
...                                                 ...   
1342  Decentralized contact tracing system supportin...   
1343           :whale2: JupyterHub Docker configuration   
1344  Concatenate histories weather data collected b...   
1345                               Frontend for Tackode   
1346                                Backend for Tackode   

                                       contributors_url  archived  disabled  \
0     https://api.github.com/repos/Perishleaf/data-v...     False     False   
1     https://api.github.com/repos/vinitshahdeo/Wate...     False     False   
2     https://api.github.com/repos/WeileiZeng/red-cr...     False     False   
3     https://api.github.com/repos/oddluck/limnoria-...     False     False   
4     https://api.github.com/repos/Beor18/alm-api-ba...     False     False   
...                                                 ...       ...       ...   
1342  https://api.github.com/repos/fwcd/iot-contact-...     False     False   
1343  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
1344  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
1345  https://api.github.com/repos/Tackode/frontend/...     False     False   
1346  https://api.github.com/repos/Tackode/backend/c...     False     False   

      stargazers_count  watchers_count  forks_count  ...  has_wiki  \
0                   80              80           90  ...      True   
1                  128             128          245  ...      True   
2                   19              19            4  ...      True   
3                   33              33            8  ...      True   
4                   11              11            2  ...      True   
...                ...             ...          ...  ...       ...   
1342                 1               1            0  ...      True   
1343                 2               2            0  ...      True   
1344                 1               1            0  ...      True   
1345                 0               0            0  ...      True   
1346                 0               0            0  ...      True   

                                               homepage  \
0                                                   NaN   
1     https://vinitshahdeo.github.io/Water-Monitorin...   
2               https://weileizeng.github.io/red-cross/   
3                                                   NaN   
4     https://alm

Comprobamos cuántos repositorios tienen en sus topics palabras relacionadas:

In [81]:
df_not_in_description_new_boolean = df_not_in_description_new.topics.str.contains(pattern_description)
df_not_in_description_new_boolean

0       True
1       True
2       True
3       True
4       True
        ... 
1342    True
1343    True
1344    True
1345    True
1346    True
Name: topics, Length: 1347, dtype: object

Vemos cuántos son:

In [82]:
df_not_in_description_new_boolean.sum()

1343

In [83]:
df_not_in_description_new_filtrado = df_not_in_description_new[df_not_in_description_new_boolean.fillna(False)]
df_not_in_description_new_filtrado.shape[0]

1343

In [84]:
df_not_in_description_new_filtrado

id                             name  \
0     229502804       data-visualisation-scripts   
1     141635301          Water-Monitoring-System   
2     237388368                        red-cross   
3     170732312                 limnoria-plugins   
4     155705971                  alm-api-backend   
...         ...                              ...   
1342  268856502               iot-contact-tracer   
1343  269479371                          jupyter   
1344  269527538  OpenWeatherMap-concat-histories   
1345  270013759                         frontend   
1346  270006438                          backend   

                                   full_name  \
0      Perishleaf/data-visualisation-scripts   
1       vinitshahdeo/Water-Monitoring-System   
2                       WeileiZeng/red-cross   
3                   oddluck/limnoria-plugins   
4                     Beor18/alm-api-backend   
...                                      ...   
1342                 fwcd/iot-contact-tracer   
1343                           kclhi/jupyter   
1344  ALT-F1/OpenWeatherMap-concat-histories   
1345                        Tackode/frontend   
1346                         Tackode/backend   

                                            description  \
0     Collection of scripts for data visualisation a...   
1     Water Monitoring System is an IOT based Liquid...   
2                                              官方公示数据概览   
3                   Limnoria plugins I wrote or forked.   
4     Comenzo como desafio almundo.com y ahora estoy...   
...                                                 ...   
1342  Decentralized contact tracing system supportin...   
1343           :whale2: JupyterHub Docker configuration   
1344  Concatenate histories weather data collected b...   
1345                               Frontend for Tackode   
1346                                Backend for Tackode   

                                       contributors_url  archived  disabled  \
0     https://api.github.com/repos/Perishleaf/data-v...     False     False   
1     https://api.github.com/repos/vinitshahdeo/Wate...     False     False   
2     https://api.github.com/repos/WeileiZeng/red-cr...     False     False   
3     https://api.github.com/repos/oddluck/limnoria-...     False     False   
4     https://api.github.com/repos/Beor18/alm-api-ba...     False     False   
...                                                 ...       ...       ...   
1342  https://api.github.com/repos/fwcd/iot-contact-...     False     False   
1343  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
1344  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
1345  https://api.github.com/repos/Tackode/frontend/...     False     False   
1346  https://api.github.com/repos/Tackode/backend/c...     False     False   

      stargazers_count  watchers_count  forks_count  ...  has_wiki  \
0                   80              80           90  ...      True   
1                  128             128          245  ...      True   
2                   19              19            4  ...      True   
3                   33              33            8  ...      True   
4                   11              11            2  ...      True   
...                ...             ...          ...  ...       ...   
1342                 1               1            0  ...      True   
1343                 2               2            0  ...      True   
1344                 1               1            0  ...      True   
1345                 0               0            0  ...      True   
1346                 0               0            0  ...      True   

                                               homepage  \
0                                                   NaN   
1     https://vinitshahdeo.github.io/Water-Monitorin...   
2               https://weileizeng.github.io/red-cross/   
3                                                   NaN   
4     https://alm

Como vemos, todos los repositorios que no tenían palabras claves en el nombre ni en la descripción, tienen topics relacionados con la COVID-19.

---

In [62]:
df_res_final

id                          name  \
0       238316428                      COVID-19   
1       235374822                      COVID-19   
2       239777191                   coronavirus   
3       237129709                   coronavirus   
4       234936988                          ncov   
...           ...                           ...   
178037  267352452                steam-lockdown   
178047  267575087            Smart-Food-Storage   
178050  246130172                     Airplanes   
178051  267858096  face_mask_detection_openvino   
178067  269906994           face-mask-detection   

                                   full_name  \
0                    CSSEGISandData/COVID-19   
1                     midas-network/COVID-19   
2                    RamiKrispin/coronavirus   
3                  FoldingAtHome/coronavirus   
4                            nextstrain/ncov   
...                                      ...   
178037      digital-wellbeing/steam-lockdown   
178047         m-boutaleb/Smart-Food-Storage   
178050                   cgettings/Airplanes   
178051  mmphego/face_mask_detection_openvino   
178067    jahnavi-prasad/face-mask-detection   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178037  How has gaming changed during lockdown? Analys...   
178047  An intelligent application (very useful during...   
178050  Visualizing flights into LGA at the start of t...   
178051  Detect faces and determine whether people are ...   
178067  Simple project to detect if a person is wearin...   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178037  https://api.github.com/repos/digital-wellbeing...     False     False   
178047  https://api.github.com/repos/m-boutaleb/Smart-...     False     False   
178050  https://api.github.com/repos/cgettings/Airplan...     False     False   
178051  https://api.github.com/repos/mmphego/face_mask...     False     False   
178067  https://api.github.com/repos/jahnavi-prasad/fa...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178037                 0               0            0  ...          True   
178047                 0               0            0  ...          True   
178050                 0               0            0  ...          True   
178051                35              35           11  ...          True   
178067                 6               6            7  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1           True                                                

Finalmente, volvemos a actualizar *df_res_final* con los 1.343 repositorios anteriores:

In [70]:
df_res_final = df_res_final.append(df_not_in_description_new_filtrado.drop(columns=['topics']))
df_res_final

id                             name  \
0       238316428                         COVID-19   
1       235374822                         COVID-19   
2       239777191                      coronavirus   
3       237129709                      coronavirus   
4       234936988                             ncov   
...           ...                              ...   
178062  268856502               iot-contact-tracer   
178063  269479371                          jupyter   
178065  269527538  OpenWeatherMap-concat-histories   
178068  270013759                         frontend   
178069  270006438                          backend   

                                     full_name  \
0                      CSSEGISandData/COVID-19   
1                       midas-network/COVID-19   
2                      RamiKrispin/coronavirus   
3                    FoldingAtHome/coronavirus   
4                              nextstrain/ncov   
...                                        ...   
178062                 fwcd/iot-contact-tracer   
178063                           kclhi/jupyter   
178065  ALT-F1/OpenWeatherMap-concat-histories   
178068                        Tackode/frontend   
178069                         Tackode/backend   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178062  Decentralized contact tracing system supportin...   
178063           :whale2: JupyterHub Docker configuration   
178065  Concatenate histories weather data collected b...   
178068                               Frontend for Tackode   
178069                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178062  https://api.github.com/repos/fwcd/iot-contact-...     False     False   
178063  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
178065  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178068  https://api.github.com/repos/Tackode/frontend/...     False     False   
178069  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178062                 1               1            0  ...          True   
178063                 2               2            0  ...          True   
178065                 1               1            0  ...          True   
178068                 0               0            0  ...          True   
178069                 0               0            0  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1   

Y lo exportamos a CSV:

In [71]:
df_res_final.to_csv(r'dataset_repositorios_filtrados.csv', index=False, encoding="utf-8-sig")

--------

### Repositorios con keywords relacionadas creados antes de 2020

Como se vio en el análisis manual del Notebook de Visualizaciones en la sección "Repositorios creados antes de declararse pandemia", la lista de repositorios no relacionados con creación previa a enero de 2020 es la siguiente:

In [2]:
invalidos = [2618529, 7797677, 34158241, 42319556, 42321742, 46790113, 63896251, 64085813, 106683801, 105979787, 
             183196269, 196332961, 225646868, 195876578,  209656058, 231134405, 216056228, 140326771, 172798234, 
             229122289, 21244714, 93610140, 175701328, 194225243, 150090997, 197573508, 213540232]

In [22]:
df = pd.read_csv('dataset_repositorios_filtrados.csv')

In [23]:
df_sin_invalidos = df[~df['id'].isin(invalidos)]
df_sin_invalidos

id                             name  \
0       238316428                         COVID-19   
1       235374822                         COVID-19   
2       239777191                      coronavirus   
3       237129709                      coronavirus   
4       234936988                             ncov   
...           ...                              ...   
178061  268856502               iot-contact-tracer   
178062  269479371                          jupyter   
178063  269527538  OpenWeatherMap-concat-histories   
178064  270013759                         frontend   
178065  270006438                          backend   

                                     full_name  \
0                      CSSEGISandData/COVID-19   
1                       midas-network/COVID-19   
2                      RamiKrispin/coronavirus   
3                    FoldingAtHome/coronavirus   
4                              nextstrain/ncov   
...                                        ...   
178061                 fwcd/iot-contact-tracer   
178062                           kclhi/jupyter   
178063  ALT-F1/OpenWeatherMap-concat-histories   
178064                        Tackode/frontend   
178065                         Tackode/backend   

                                              description  \
0       Novel Coronavirus (COVID-19) Cases, provided b...   
1                       2019 novel coronavirus repository   
2                                 The coronavirus dataset   
3                           Folding@home COVID-19 efforts   
4       Nextstrain build for novel coronavirus SARS-CoV-2   
...                                                   ...   
178061  Decentralized contact tracing system supportin...   
178062           :whale2: JupyterHub Docker configuration   
178063  Concatenate histories weather data collected b...   
178064                               Frontend for Tackode   
178065                                Backend for Tackode   

                                         contributors_url  archived  disabled  \
0       https://api.github.com/repos/CSSEGISandData/CO...     False     False   
1       https://api.github.com/repos/midas-network/COV...     False     False   
2       https://api.github.com/repos/RamiKrispin/coron...     False     False   
3       https://api.github.com/repos/FoldingAtHome/cor...     False     False   
4       https://api.github.com/repos/nextstrain/ncov/c...     False     False   
...                                                   ...       ...       ...   
178061  https://api.github.com/repos/fwcd/iot-contact-...     False     False   
178062  https://api.github.com/repos/kclhi/jupyter/con...     False     False   
178063  https://api.github.com/repos/ALT-F1/OpenWeathe...     False     False   
178064  https://api.github.com/repos/Tackode/frontend/...     False     False   
178065  https://api.github.com/repos/Tackode/backend/c...     False     False   

        stargazers_count  watchers_count  forks_count  ...  has_projects  \
0                  27211           27211        17432  ...          True   
1                    642             642          221  ...          True   
2                    394             394          175  ...          True   
3                   1115            1115           87  ...          True   
4                   1208            1208          343  ...          True   
...                  ...             ...          ...  ...           ...   
178061                 1               1            0  ...          True   
178062                 2               2            0  ...          True   
178063                 1               1            0  ...          True   
178064                 0               0            0  ...          True   
178065                 0               0            0  ...          True   

        has_wiki                                           homepage  \
0           True  https://systems.jhu.edu/research/public-health...   
1   

Exportamos con el dataset actualizado:

In [24]:
df_sin_invalidos.to_csv(r'dataset_repositorios_filtrados_final.csv', index = False, encoding="utf-8-sig")